### ISSUE TITLE
Contact List - Add button is enabled even in the Unassigned and Unapproved Employees tabs

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#100]
The add button is still enabled even if I jump to Unassigned Employee tab and Unapproved Employee tab

**To Reproduce**
1. From the Team Details Tab, click the Unassigned Employee Tab
2. Click the add button
3. Close the Insert Contact pop-up window
4. From the Unassigned Employee Tab, click the Unapproved Employee Tab
5. Click the add button
6. Close the Insert Contact pop-up window

**Expected behavior**
When jumping from Team details to Unassigned Employee tab and Unapproved Employee tab and vice versa, Add button should only be enabled when the Team details tab is selected.

**Screenshots**
![Enabled Add Button](https://user-images.githubusercontent.com/53286096/61851997-f22b1200-aeea-11e9-985e-2022816c32d4.jpg)

**Comment by jester0123** [comment]
@chloecastillo 
Hi Ms. CC. We will add this concern on our next iteration. Thank you.

**Comment by jester0123** [comment]
@chloecastillo 
Marking this one as resolve. This will reflect on next build.
