### ISSUE TITLE
Attendance - Incomplete list of resources base on the current Contact List

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#101]
**Describe the bug**
Attendance - Resource Planner has an incomplete list of resources if compared to the Contact List-Team details.

**To Reproduce**
1. Go to Attendance
2. Count the number of Resource list in the Resource Planner
3. Validate the Resources if it is in the Contact List - Team details

**Expected behavior**
Attendance - Resource List has the same Resource list in the Contact List - Team details

**Screenshots**

![ContactList_TeamDetails](https://user-images.githubusercontent.com/53286096/61853312-323fc400-aeee-11e9-9aa1-b5389bd37850.jpg)
![Attendance_ResourcePlanner](https://user-images.githubusercontent.com/53286096/61853318-353ab480-aeee-11e9-9d6c-2d67cd6e9154.jpg)

**Comment by jhunellbarcenas** [comment]
@chloecastillo 
This is not considered as issue or bug. Attendance Module will only have a record when certain users(employees) login to AIDE app same goes with the attendance dashboard. Considered as close
