### ISSUE TITLE
Attendance - Leave Application window has a Resource not in the Contact List - Team Details

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#102]
Resource that is not visible in the Contact List - Team details is available in the Resource Planner Leave Application window.

**To Reproduce**
1. Go to Attendance
2. Click Add button from the Resource Planner window
3. Validate the list of Resources against the Contact List - Team details

**Expected behavior**
Leave application - Resource list has the same data with Contact List - Team details 

**Screenshots**
![Attendance_ResourcePlanner Leave App ResourceList](https://user-images.githubusercontent.com/53286096/61854903-a29c1480-aef1-11e9-9e93-28be7b4a639e.jpg)

**Comment by jsanchez-cwt** [comment]
Fixed
