### ISSUE TITLE
Task - Task Monitoring has Resources that are not visible in Contact List - Team details

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#103]
The Resources in the Task Monitoring window is not the same as the one listed in the Contact List.

**To Reproduce**
1. Go to Task
2. Validate list of Resources in the Task Monitoring window

**Expected behavior**
Task Monitoring has the same resources with Contact List - Team details

**Screenshots**
![ContactList_TeamDetails](https://user-images.githubusercontent.com/53286096/61855353-7c2aa900-aef2-11e9-901b-be1b8ab73868.jpg)
![Task_Task Monitoring](https://user-images.githubusercontent.com/53286096/61855427-a1b7b280-aef2-11e9-8517-2475d46b56cb.jpg)

**Comment by jsanchez-cwt** [comment]
Fixed.
