### ISSUE TITLE
Skills - Skills Matrix has Resources that are not visible in Contact List - Team details

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#104]
The Resources in the Skills Matrix is not the same as the one listed in the Contact List.

To Reproduce
1. Go to Skills
2. Validate list of Resources in the Skills Matrix

Expected behavior
Skills Matrix Resources has the same resources with Contact List - Team details

**Screenshots**
![ContactList_TeamDetails](https://user-images.githubusercontent.com/53286096/61855689-23a7db80-aef3-11e9-8cdf-65b74e319e23.jpg)
![Skills_Skills Matrix Resources](https://user-images.githubusercontent.com/53286096/61855701-27d3f900-aef3-11e9-9784-08d135a28393.jpg)

**Comment by jsanchez-cwt** [comment]
This issue is now resolved.
