### ISSUE TITLE
Add asterisk(*) on the fields that are Mandatory

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#105]
Asterisk as an identifier for Mandatory/Required fields make the users aware of the items they need to fill-up. This prevents them from go back and forth to the screen wondering what else needs to be entered.

**Comment by jhunellbarcenas** [comment]
Duplicate of #93 
@chloecastillo

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.6
