### ISSUE TITLE
Skills Matrix (All Employee) should only be visible to Leads and Managers

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#106]
Recommendation:
Full Details (All Employee) should only be visible to Managers and Leads can only see the details of his team. The responsibility of updating the details should be given to the resource which means that the resources can only see their data unless otherwise they are tagged as a Lead/Manager. This will help in the performance of the application.

**Comment by charissasylim** [comment]
This is a non-issue. Sense and Respond Comm Cell Board promotes go and see so team skills should be visible to everyone.

**Comment by charissasylim** [comment]
Consider closed.
