### ISSUE TITLE
Contact Details like Birth date and home phone should not be visible to other users

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#107]
[Confidentiality] As this is a personal data that cannot be shared to others, this should not be visible to every user.

**Comment by jester0123** [comment]
@chloecastillo 
Hi CC, only the managers and yourself can view your personal details. Others wont be able to see it.

**Comment by jester0123** [comment]
@chloecastillo 
This is considered closed. Thank you.
