### ISSUE TITLE
Change Label Work Mobile in Contact List table to 'Mobile Number'

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#110]
Change Label Work Mobile in Contact List table to 'Mobile Number'

**Comment by jhunellbarcenas** [comment]
Hi @jester0123 assigning this to you since you have a major change on this module... so we won't have to encounter any conflicts when merging. Thanks.

**Comment by jester0123** [comment]
@charissasylim @jhunellbarcenas 
Done with this. This will reflect on next build
