### ISSUE TITLE
Assets: Partially Assigned/Unassigned Does Not Show Up in For Approval

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#111]
**Describe the bug**
Partially Assigned/Unassigned Asset Does Not Show Up in For Approval in order for asset to be moved to Assigned/Unassigned state

**To Reproduce**
1. Asset Assignment --> All Asset
Assigned To: Cha
Status: Unassigned
2. Update Asset to set as 'Assigned'. Status changes to Partially Assigned.
Asset does not show up in List of Unapproved Assets.
Status is always Partially Assigned.

**Expected behavior**
Asset should be listed in List of Unapproved Assets.

**Screenshots**

**Version (please complete the following information):**
 - Version 2.5

**Additional context**

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.6
