### ISSUE TITLE
Unable to Close Action Item before Due Date

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#112]
**Describe the bug**
Unable to close action item before the due date.
Error message 'Date Should be not the Day Before Selected From Date!'.

**To Reproduce**
1. Action item has due date of 7/31/2019
2. Update close date to 7/30/2019
2. Error message appears

**Expected behavior**
Allow action item to be closed anytime

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62106827-cd62e000-b2d8-11e9-980b-6095f0381c41.png)

**Version (please complete the following information):**
 - Version 2.5

**Additional context**

**Comment by jhunellbarcenas** [comment]
Fixed. Removed this error message to allow action item to be closed anytime.
Ready for v2.6
