### ISSUE TITLE
Display the current AIDE version on the main UI

### ISSUE THREAD

**Issue by trashvin** [rsx-labs/aide-frontend#113]
**Is your feature request related to a problem? Please describe.**
Reporting an issue / bug is more detailed if the version can be easily seen on the UI ( i.e. screenshots submitted can clearly show the version). The displayed version can can also aid (pun intended :)) AIDE users if their update was successful. For developers, they can easily say that the issue does exist or the function is not supported by just looking at the version.

**Describe the solution you'd like**
Make the current version number visible ( i.e. at the lower or upper part of the screen). 

**Describe alternatives you've considered**
If its aesthetically not pleasing, place the version in the About Page.

**Additional context**
None

**Comment by jsanchez-cwt** [comment]
Ready for version 2.6
