### ISSUE TITLE
Allow Asset Inventory Deletion

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#115]
Allow an asset to be deleted using a flag for cases when asset is disposed, move to different dept or team. Allow deletion by manager only.

Add a tab for deleted assets.

**Comment by jhunellbarcenas** [comment]
For next build (2.7)

**Comment by charissasylim** [comment]
If move to different dept or team, maybe show a dropdown of team name.. then can automatically assign to manager of team or can show dropdown of managers for that team.. transfer of asset to another team should assign only to manager for that team and not directly to members.

Asset deletion is used when asset is disposed or asset is moving to another department when employee is moved to another department. Need reason for deletion as required field.

**Comment by charissasylim** [comment]
use deleted flag instead of physical deletion from database

**Comment by charissasylim** [comment]
@jhunellbarcenas any chance this can get into build 2.9.0?

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for next build

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
