### ISSUE TITLE
Project ID isn't available error when creating a Project

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#119]
**Describe the bug**
An error was received after entering details of the project to be created.

**To Reproduce**
1. Click Project
2. Enter details of the project to be created
3. Click 'Create' button

**Expected behavior**
Project created is saved/created.

**Screenshots**
![Create Project](https://user-images.githubusercontent.com/53286096/62278855-7cd7b800-b47b-11e9-9298-1558dd1132ec.jpg)

**Comment by charissasylim** [comment]
Closing this due to Project screen overhaul.
