### ISSUE TITLE
Comcell Clock - :00 input is saved as 0

### ISSUE THREAD

**Issue by jhunellbarcenas** [rsx-labs/aide-frontend#121]
**Describe the bug**
Inserting/Updating comcell clock minutes to :00 is saved as 0.

**To Reproduce**

**Expected behavior**
Expected behavior should be :00

**Screenshots**

**Version (please complete the following information):**

**Additional context**

**Comment by jester0123** [comment]
Fixed. Ready for next build.

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by ellaineronquillo** [comment]
Closed 10/17/19
