### ISSUE TITLE
Weekly Report - Unable to get the new Tasks created on the working status.

### ISSUE THREAD

**Issue by jsanchez-cwt** [rsx-labs/aide-frontend#126]
**Describe the bug**
The new tasks created are unable to fetch on the weekly report on the working status.

**To Reproduce**
**Pre-req**
1. The weekly report is on working status. (Not submitted yet).
2. Create a new task on the Task window.

**Steps**
1. Go to 'Weekly Report' tab.
2. Click the report with 'Working' status.
3. The new task was unable to fetch.

**Expected behavior**
The newly created task should be fetched and display on the working status.

**Version (please complete the following information):**
 - Version 2.6.0

**Additional context**
None

**Comment by charissasylim** [comment]
@johnharveysanchez7 Harvey, can you look into this instead please?
