### ISSUE TITLE
Billability - Vacation Leave Module add total number of leaves

### ISSUE THREAD

**Issue by jhunellbarcenas** [rsx-labs/aide-frontend#127]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It may be a legend for the computation of total number of leaves or just simply display total number of employee's leave

**Describe alternatives you've considered**

**Additional context**

**Comment by jester0123** [comment]
Fixed. Ready for v2.7 build

**Comment by jester0123** [comment]
For QA testing 2.7 build

**Comment by ellaineronquillo** [comment]
Closed 10/17/19
