### ISSUE TITLE
Contact List - Received 'Nullable object must have value' Error when inserting a new contact

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#128]
**Describe the bug**
After providing all required fields for the new contact, an error "'Nullable object must have value' " was received after clicking the Create button.

**To Reproduce**
1. Go to 'Contact List'
2. Click on '+' button from the Team details tab
3. Provide required details of the new contact.
4. Click 'Create' button

**Expected behavior**
New Contact is created

**Screenshots**
![Insert Contacts](https://user-images.githubusercontent.com/53286096/62524453-41b4fa80-b868-11e9-9bce-04f5e887a32d.jpg)
![Insert Contacts2](https://user-images.githubusercontent.com/53286096/62524464-45e11800-b868-11e9-9212-e6367d0b7f71.jpg)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Hi po @chloecastillo 
This is due to validations of entry fields for employee ID and middle initial.

Employee ID should only have 8 digits
Middle Initial should only have 1-2 characters?

We will implement this issue on next build.

**Comment by jester0123** [comment]
Fixed. Ready for v2.7 build

**Comment by jester0123** [comment]
For QA Testing v2.7 build

**Comment by ellaineronquillo** [comment]
Closed 10/16/19
