### ISSUE TITLE
Contact List - Insert Contact fields has no number/character limit set

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#129]
**Describe the bug**
Entered more than 8 numbers in Employee ID and more than 1 character for Middle initial and the field displayed all the numbers/letters. No number/character limit set.

**To Reproduce**
1. Go to 'Contact List'
2. Click on '+' from Team Details Tab
3. Enter more than 8 characters for Employee ID and Middle Initial

**Expected behavior**
A maximum character should be set for the fields base on its db value set.

**Screenshots**
![Insert Contacts - Fields no limit](https://user-images.githubusercontent.com/53286096/62525894-c739aa00-b86a-11e9-9bde-cacc41232c0e.jpg)

**Version (please complete the following information):**
 - Version 2.6

**Additional context**

**Comment by jhunellbarcenas** [comment]
This is due to no validation for the employee ID and middle initial fields.

We will cover this on next build. Thanks

**Comment by jester0123** [comment]
Employee ID maxlength was now set to 9
Middle initial maxlength is now set to 2
Middle initial, First & Last name will only accept character strings.

Fixed on build 2.7

**Comment by jester0123** [comment]
For QA Testing v2.7 build

**Comment by ellaineronquillo** [comment]
Closed 10/16/19
