### ISSUE TITLE
[Reports] Display Reports in AIDE

### ISSUE THREAD

**Issue by jhunellbarcenas** [rsx-labs/aide-frontend#13]
- Not printing all data only prints current datagrid items

@harvex007 has fixed other functions except **Assets**

**Comment by charissasylim** [comment]
@IvanArtigo can you please look into adding/fixing the print option in AIDE. Check if export is better than print functionality. The goal is to enable teams with no developers/DB knowledge to be able to extract data from the UI. Simple layout of data is OK.

**Comment by charissasylim** [comment]
@jhunellbarcenas @johnharveysanchez7 @GiannCarlo @jester0123 @trashvin 
Marvin created this reports site http://10.158.47.100:8081/  
We can have a reports module that would call the links to the report sites.
