### ISSUE TITLE
Contact List Column 'Nick Name' change to 'Nickname'

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#130]
**Describe the bug**
Contact List Column 'Nick Name' change to 'Nickname'

**Version (please complete the following information):**
 - Version 2.6

**Comment by jester0123** [comment]
Fixed. Ready for v2.7 build

**Comment by jester0123** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed Fixed in v2.8.0
