### ISSUE TITLE
Insert Contacts labels and data consistency

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#131]
**Describe the bug**
Insert Contacts screen
- Under Personal Details
1. Change 'Select Marital Status' to 'Select marital status'
2. Change 'Select Workshift' to 'Select workshift'
3. Update 'Select permission' data from 'Manager' to 'Manager level'

- Under Contact Details
1. Change 'Enter nick name' to 'Enter nickname'
2. Update 'Select work location' data  from 'Durham' to 'Raleigh, Durham'
3. Remove 'Raleigh' from 'Select work location' data

**Version (please complete the following information):**
 - Version 2.6

**Comment by charissasylim** [comment]
Under Contact Details
1. Change 'Select job position' to 'Select position'

**Comment by jester0123** [comment]
Fixed. Ready for v2.7 build

**Comment by jester0123** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed Fixed on v2.8.0
