### ISSUE TITLE
Update Contacts label and data consistency

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#132]
**Describe the bug**
Update Contacts

Under Personal Details
1.  Change 'Permission Group' to 'Permission'.

Under Contact Details
1. Change 'Nick Name' to 'Nickname'.
2. Update 'Work Location' data from 'Durham' to 'Raleigh, Durham'.
3. Remove 'Raleigh' from 'Work Location'.

**Version (please complete the following information):**
 - Version 2.6

**Additional context**

**Comment by jester0123** [comment]
Fixed. Ready for v2.7 build

**Comment by jester0123** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
#2 and #3 Confirmed Fixed in v2.8.0.
 Will open another ticket for item number 1
