### ISSUE TITLE
Change 'Contact Lists' header to 'Contacts List'

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#133]
**Describe the bug**
Change 'Contact Lists' header to 'Contacts List'

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62585861-7fa83200-b8ed-11e9-8c2b-7c2d3b59c77f.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jester0123** [comment]
Fixed. Ready for v2.7 build

**Comment by jester0123** [comment]
Fixed. Ready for v2.7 build

**Comment by jester0123** [comment]
For QA testing 2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed in v2.8.0
