### ISSUE TITLE
Resource Planner legends on 2 different font size

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#134]
**Describe the bug**
Resource Planner legends on 2 different font size

**Expected behavior**
Font size should be the same and consistent for same context

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62585918-c5fd9100-b8ed-11e9-8587-a60ac739c56b.png)

**Version (please complete the following information):**
 - Version 2.6

**Additional context**

**Comment by jhunellbarcenas** [comment]
@jester0123  Please look into this. I think this is just because of the width set? Thank you.

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7 build

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed in v2.8.0
