### ISSUE TITLE
Task Monitoring employee name missing comma after last name

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#135]
**Describe the bug**
Task Monitoring employee name missing comma after last name

**Expected behavior**
Comma after last name before first name to be consistent with all other screens with employee names

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62586031-52a84f00-b8ee-11e9-9519-a1fd71464655.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7 build

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed in v2.8.0
