### ISSUE TITLE
Add Task 'Status' Data Change from 'Returned to Triage' to 'Returned to Submitter'

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#136]
**Describe the bug**
Add Task 'Status' Data Change from 'Returned to Triage' to 'Returned to Submitter'

**Expected behavior**
Change 'Triage' to 'Submitter' to be more user friendly for other departments in case

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for build v2.7

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed in v2.8.0
