### ISSUE TITLE
Set a value for Sick Leave 'Select Fiscal Year' dropdown list upon screen display

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#137]
**Describe the bug**
Set a value for Sick Leave 'Select Fiscal Year' dropdown list upon screen display to show current FY being displayed to be consistent with other screens.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62586275-75873300-b8ef-11e9-9974-b012dce5c965.png)

**Version (please complete the following information):**
 - Version 2.6

**Additional context**

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for build v2.7

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed in v2.8.0
