### ISSUE TITLE
Set a value for Vacation Leaves 'Select Fiscal Year' dropdown list upon screen displacy

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#138]
**Describe the bug**
Set a value for Vacation Leaves 'Select Fiscal Year' dropdown list upon screen display to show current FY being displayed to be consistent with other screens.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62586326-a7989500-b8ef-11e9-8d9a-7c00931c9d99.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for build v2.7

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed in v2.8.0
