### ISSUE TITLE
Use First name instead of nickname for Non Billable Hours per person

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#139]
**Describe the bug**
Use First name instead of nickname for Non Billable Hours per person to be consistent with other screens

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62586375-e75f7c80-b8ef-11e9-9e6d-49d0815cf745.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for build v2.7

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed in v2.8.0
