### ISSUE TITLE
Weekly Report Missing Reports 'ALL REPORTS HAVE BEEN SUBMITTED.'

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#140]
**Describe the bug**
Is that a comma at the end of the 'ALL REPORTS HAVE BEEN SUBMITTED'? Just in case, please ensure it is a period instead of a comma.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62586442-3ad1ca80-b8f0-11e9-9466-fbb6b5663cea.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed in v2.8.0
