### ISSUE TITLE
Add Weekly Report Labels Consistency

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#141]
**Describe the bug**
1. Change 'Please fill up all required field.' to 'Please fill up all required fields.' (added s to field)
2. Change 'Select project *' to 'Select a project *'
3. Change 'Reference ID' to 'Enter a reference ID'. (this field is required in Add Task. Is this field required in Weekly report?)
4. Change 'Subject *' to 'Enter description *'
5. Change 'Severity' to 'Select severity'
6. Change 'Incident type' to'Select a category *'' (this field is required in Add Task. Is this field required in Weekly report?)
7. Change 'Comments' to 'Enter comments'
8. Change 'Phase' to 'Select phase' (this field is required in Add Task. Is this field required in Weekly report?)
9. Change 'Status *' to 'Select a status *'
10. Change 'Estimate effort(hrs) to 'Enter estimate effort(hrs).
11. Change 'Actual effort for the week(hrs) *' to 'Enter actual effort(hrs) for the week *'
12. Change 'Actual effort(hrs) *' to 'Enter actual effort(hrs) *'

**Expected behavior**
Changes are to ensure consistency of labels with Add Task

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62586866-0101c380-b8f2-11e9-9c2f-44cd67c038bb.png)

**Version (please complete the following information):**
 - Version 2.6

**Additional context**

**Comment by charissasylim** [comment]
Apply the same changes to Update Weekly Report screen

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7 build

@charissasylim Reference ID is not a required field here in weekly reports because leaves does not require a reference ID same goes with category and phase

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed in v2.8.0
