### ISSUE TITLE
Weekly Report Columns Updates

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#142]
**Describe the bug**
Update Weekly Report Columns for consistency with task and for user friendliness with other department.

1. Change 'Subject' to 'Description'
2. Change 'Incident Type' to 'Category'
3. Change 'Date Started' to 'Start Date'
4. Change 'Date Finished' to 'Completed Date'

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62587176-3529b400-b8f3-11e9-8803-93af5228acc1.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
No longer applicable in the new UI for v2.8.0
