### ISSUE TITLE
Add 3 C label consistency

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#143]
**Describe the bug**
Change 'Enter a counter measure *' to 'Enter a countermeasure *' making countermeasure 1 word instead of 2

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62587268-aa958480-b8f3-11e9-8077-926343b1019d.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7 build

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed in v2.8.0
