### ISSUE TITLE
Lessons Learnt label consistency

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#144]
**Describe the bug**
Change 'Search lesson's learnt' label to 'Search lessons learnt' removing the apostrophe in the word lessons

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62587352-21328200-b8f4-11e9-998a-a42755aa722f.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7 build

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed in v2.8.0
