### ISSUE TITLE
Add Lessons Learnt label consistency

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#145]
**Describe the bug**
Change 'Add Lesson's Learnt' to 'Add Lessons Learnt' to remove apostrophe in the word Lessons

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62587384-49ba7c00-b8f4-11e9-9e02-c387bc9af25c.png)

**Version (please complete the following information):**
 - Version 2.6

**Additional context**

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7 build

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed in v2.8.0
