### ISSUE TITLE
Success Registers label correction

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#146]
**Describe the bug**
'Change 'Who's Involve' to 'Who's Involved'

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62587452-a7e75f00-b8f4-11e9-8e8f-80e70c263212.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed in v2.8.0
