### ISSUE TITLE
Create Success Register label correction

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#147]
**Describe the bug**
Change 'Select who's involve *' to 'Select who's involved *' adding letter d to involve

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62587488-d6fdd080-b8f4-11e9-8ec5-a2d542f05d2d.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed v2.8.0
