### ISSUE TITLE
Employee names in Improvements 

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#148]
**Describe the bug**
1. 3 C - User First name for Owner
2. Action List - Use First name for Assignee
3. Lessons Learnt - Use First name for Raised By
4. Success Registers - Use First name for Who's Involved
5. Success Registers - Use First name for Raised By

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed v2.8.0
