### ISSUE TITLE
Skills Matrix Screen Overhaul

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#149]
**Describe the bug**
1. Remove picture and other employee details since those can be seen in contact list already unless there is a specific reason for them to be displayed then please discuss with me.
2. See screenshot for upper screen UI adjustments..
3. Change 'Edit My Skill' to 'Edit My Skills' with s on the word Skill.
4. Change 'View All Employee' to 'View All Employees' with s on the word Employee.
5. Remove the Employee ID column on the table unless there is a specific reason for them to be displayed then please discuss with me.
6. Change Employee Name display format to Last Name comma First Name to be consistent with other screens. Example, SANTOS, CHARISSA

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62588534-9acc6f00-b8f8-11e9-8635-32f8b47c73c5.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed v2.8.0
