### ISSUE TITLE
Attendance - Insert holidays issue

### ISSUE THREAD

**Issue by jhunellbarcenas** [rsx-labs/aide-frontend#15]
- inserting holidays to exclude employees who are not in PH.

**Comment by jhunellbarcenas** [comment]
Fixed. updated sp_UpdateResourcePlanner.sql

**Comment by jhunellbarcenas** [comment]
Do not allow user level employees to file a Holiday.
Exclude holiday from the drop down list

**Comment by charissasylim** [comment]
@jhunellbarcenas is this fixed already? If yes, please close.

**Comment by jhunellbarcenas** [comment]
@charissasylim the issue for this one is that when on user level profile holiday status is still showing on the list of leave types this should not appear because only manager level should file a holiday type of leave.

**Comment by charissasylim** [comment]
@jhunellbarcenas ok please exclude holiday from dropdown for user level

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for next build v2.8

**Comment by ellaineronquillo** [comment]
Closed 10/17/19
