### ISSUE TITLE
Update Asset Screen gaps and data updates

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#150]
**Describe the bug**
1. Is it possible to remove the gaps in between fields? 
2. Can Created by display the name instead of ID number during updates?

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62588840-c734bb00-b8f9-11e9-95e4-e470fbaf8bda.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by charissasylim** [comment]
@jester0123 have you started working on this? if not, do you think you can insert this task in your workload?

**Comment by jester0123** [comment]
@charissasylim just started working on the task ma'am.

**Comment by jester0123** [comment]
Merged. Ready for next build

**Comment by charissasylim** [comment]
Confirmed fixed in 2.8.0
