### ISSUE TITLE
Create Project label consistency

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#151]
**Describe the bug**
1. Change 'Select Category' to 'Select category' using lowercase on the word category

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62589321-7b831100-b8fb-11e9-8756-8c8a5b5a8a9b.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed v2.8.0
