### ISSUE TITLE
Assign Project name display

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#152]
**Describe the bug**
1. Change 'Name' to 'Employee Name'.
2. Add missing comma after last name and before first name.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62589407-c43aca00-b8fb-11e9-86ca-917d96122ae3.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed v2.8.0
Name was not renamed in the fix though
