### ISSUE TITLE
Team Commendations label consistency

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#153]
**Describe the bug**
1. Change 'Sent by *' to 'Enter sent by *'.
2. Change 'Write commendation reason *' to 'Enter commendation reason *'

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62589527-1da2f900-b8fc-11e9-93bb-f502a6f3a31e.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by charissasylim** [comment]
For check-in.

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed v2.8.0
