### ISSUE TITLE
Tracker label consistency

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#154]
**Describe the bug**
1, Change 'Search a tracker course' to 'Search a tracker' to remove the word course

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62589668-91dd9c80-b8fc-11e9-8c34-f5d85bc8f452.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by charissasylim** [comment]
Missing an icon?
![image](https://user-images.githubusercontent.com/52391236/62589718-c7828580-b8fc-11e9-8f1d-ab7754340c38.png)

**Comment by jester0123** [comment]
Fixed. Ready for next build

**Comment by jester0123** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed v2.8.0
