### ISSUE TITLE
Comm cell Meeting label consistency and default values setting on screen

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#155]
**Describe the bug**
1. Header is missing an icon. See screenshot and compare with other screens.
2. Change tab label from 'Commcell Meeting' to 'Comm. Cell Meeting'
3. Change header from 'Commcell Meeting' to 'Comm. Cell Meeting'.
4.  Set a value for 'Select Fiscal Year' dropdown list upon screen display to show current FY being displayed to be consistent with other screens.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62589978-86d73c00-b8fd-11e9-8175-9ee8015fbd97.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed just needs to add icon on header.

**Comment by jhunellbarcenas** [comment]
@jester0123 Please provide the icon for this module

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7 build

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed in v2.8.0
