### ISSUE TITLE
Update Facilitator and Minutes Taker

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#156]
**Describe the bug**
Display the labels on the fields as done with all other screens in AIDE.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62590209-2d234180-b8fe-11e9-80e7-54866cf8a455.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed v2.8.0
