### ISSUE TITLE
Add Facilitator and Minutes Taker

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#157]
**Describe the bug**
1. Facilitator list should be first name last name format like other dropdown list in AIDE.
2. Minutes taker should be first name last name format like other dropdown list in AIDE.

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7 build

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed v2.8.0
Format lastname,firstname like all other screens.
