### ISSUE TITLE
Late Tracking label consistency and default values setting

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#158]
**Describe the bug**
1. Set a value for Late for the Fiscal Year  dropdown list upon screen display to show current FY being displayed to be consistent with other screens.
2. Change 'Select Year' to 'Select Fiscal Year'
3. Set a value for Late for the Month dropdown list upon screen display to show current month being displayed to be consistent with other screens.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62590414-d5d1a100-b8fe-11e9-857e-f23b31dbd673.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7 build

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed on v2.8.0
