### ISSUE TITLE
Redesign Contributors table to remove link to contacts

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#161]
Redesign Contributors table to not require link to Contacts table.
Instead of storing EMP_ID, store the contributor name instead.
Remove picture and position from UI. Just list the names of contributors.

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed in v2.8.0
