### ISSUE TITLE
Resource Planner - Leave Type is accepting blank/null

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#162]
**Describe the bug**
After providing details of the leave, I left the Leave type blank and tried to save the Leave, and it was saved

**To Reproduce**
1. Go to 'Resource Planner'
2. Click on '+' and select a Resource, enter details of the leave but do not enter anything for the Leave Type.
3. Click 'Create' button

**Expected behavior**
Leave should not be saved as Leave type is a required field.

**Screenshots**
![Leave App -Leave Type Blank](https://user-images.githubusercontent.com/53286096/62612812-cf611a80-b93a-11e9-98a7-6e558d179466.jpg)
![Leave App -Leave Type Blank2](https://user-images.githubusercontent.com/53286096/62612820-d2f4a180-b93a-11e9-9f4d-70c3916d6e8f.jpg)
![Leave App -Leave Type Blank3](https://user-images.githubusercontent.com/53286096/62612829-d720bf00-b93a-11e9-9763-c833cb26ccf4.jpg)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7 build

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by ellaineronquillo** [comment]
Closed 10/16/19
