### ISSUE TITLE
Billable Hours for May is displaying NaN%

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#164]
**Describe the bug**
Selecting Monthly Hours May for Billable Hours shows NaN%

**To Reproduce**
1. Go to Billability - Billable Hours
2. Select May under Monthly Hours
3. Check Billable Hours and Non Billable Hours %

**Expected behavior**
It should show numeric percentage

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/62911135-b67ebc00-bdb5-11e9-9300-44c4a9592752.png)

**Version (please complete the following information):**
 - Version 2.6

SQL Server Profiler --
exec dbo.[sp_GetBillableHoursByMonth] @EMPID=915000121,@MONTH=5,@YEAR=2019,@WEEKID=1

--executed successfully when ran in SQL Server Management Studio

**Comment by jsanchez-cwt** [comment]
The Weekly Report module was implemented last June 2019.  April and May have no data.

**Comment by charissasylim** [comment]
Ok. Please close.
