### ISSUE TITLE
Add button is not visible in some modules

### ISSUE THREAD

**Issue by jhunellbarcenas** [rsx-labs/aide-frontend#167]
**Describe the bug**
Add button is not visible in the following modules in Manager view:
- Announcement Dashboard
- Comcell Clock
- Comcell Meeting
- Tracker

**To Reproduce**
1. 'Manager' in Permissions group table is changed into 'Manager Level' for data consistency.
2. Login as Manager
2. Go to the following screens.
- Announcement Dashboard
- Comcell Clock
- Comcell Meeting
- Tracker
3. Add button is not visible

**Expected behavior**
Should be visible when user's permission group is Manager Level

**Version (please complete the following information):**
- Version 2.6 in Innovation Room
**Additional context**

**Additional Comments**
- This issue is because "Manager" from Permissions group table is changed into "Manager Level". So existing code for conditions could not handle this recent change.

**Comment by charissasylim** [comment]
Code should use the GRP_ID instead of the text in conditions.

**Comment by charissasylim** [comment]
Change is to ensure that the permission text 'Manager' is not used in condition checking for acces but instead use the GRP_ID is used so that if we change the permission description, it won't affect thefunctionality.

**Comment by chriscg** [comment]
Cannot reproduce in version 2.7.1. Add button is visible.
