### ISSUE TITLE
[Projects] Isn't project ID numerically incremental in DB?

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#170]
**Describe the bug**
Isn't project ID numerically incremental in the DB? Should this be removed from the UI instead if that's the case?

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
@charissasylim It is not numerically incremental. I think the reason for this one is that we used to think that this project ID is also meant for the project code. The plan is to have this as numerically incremental and have a separate column for project code.

**Comment by jhunellbarcenas** [comment]
@charissasylim should we proceed to removed this from the UI?

**Comment by charissasylim** [comment]
Yes but we need the screen fixed to I Claude project code

Sent from Yahoo Mail on Android 
 
  On Wed, Aug 28, 2019 at 4:38 PM, jhunellbarcenas<notifications@github.com> wrote:   
@charissasylim should we proceed to removed this from the UI?

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed Fixed in 2.8.0
