### ISSUE TITLE
[Lessons Learnt] Show action description when selecting action ref to be linked

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#171]
**Is your feature request related to a problem? Please describe.**
When selecting an action ref no to be linked to the lessons learnt, show the action message for easier selection instead of having to know the ref no..  Should this use something similar to how an action is linked to a 3C?

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for next build v2.8

**Comment by charissasylim** [comment]
Closing since Action Message might be too long in the dropdown to be displayed.
Not seeing fix also.
