### ISSUE TITLE
[Comm Cell Meeting] Remove checking if facilitator and minutes taker are the same

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#172]
**Is your feature request related to a problem? Please describe.**
Remove the checking if facilitator and minutes taker are the same to allow flexibility

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7 build

**Comment by jhunellbarcenas** [comment]
**NOTE:** @charissasylim Removing this feature will allow to have facilitator and minutes taker to be the same.

**Comment by charissasylim** [comment]
That’s ok to allow same facilitator and minutes taker.

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed 2.8.0
