### ISSUE TITLE
[3C Measure] Update '3C Measure' tab to '3C'

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#175]
**Describe the bug**
Update '3C Measure' tab to '3C'

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/63066767-4c455300-bf3e-11e9-93ba-8242575c30d9.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for 2.7 build

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed in 2.8.0
