### ISSUE TITLE
[3C] Updated 'CLOSED' 3Cs order to be order by ref no. descending

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#176]
**Is your feature request related to a problem? Please describe.**
'CLOSED' 3Cs order to be order by ref no. descending so that new 3Cs are displayed on top after 'OPEN' 3Cs. Ordeing of 'OPEN' 3C's are OK.

**Comment by jhunellbarcenas** [comment]
@charissasylim This seems to work as fine after adding a new 3C. Ordering of 3Cs are by status (Open, Close)

**Comment by charissasylim** [comment]
Can you add order by status and ref no?

**Comment by charissasylim** [comment]
ok in v 2.7.1
