### ISSUE TITLE
[3C] Why are the 'CLOSED' 3Cs highligted?

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#177]
**Describe the bug**
Why are the 'CLOSED' 3Cs highlighted? See screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/63066880-e3aaa600-bf3e-11e9-9dc5-760a7c1f207a.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
@charissasylim We couldn't replicate this issue. Also, looking into aide this incidents are not highlighted anymore don't know exactly why these happens. Looking into code it will only be highlighted once the status is open

**Comment by jhunellbarcenas** [comment]
@charissasylim Should we close this?

**Comment by charissasylim** [comment]
Reopened since it is still happening
