### ISSUE TITLE
Attendance did not show onsite after updating location

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#178]
**Describe the bug**
Attendance did not change from present to onsite after updating location from EcoTower to WFH after refresh or AIDE restart

**To Reproduce**
1. Login to AIDE. Attendance shows green present.
2. Update location from EcoTower to WFH
3. Click other screens and/or restart AIDE
4. Attendance still shows green present

**Expected behavior**
Attendance should be yellow onsite after location update.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/63231101-36d76e00-c249-11e9-8065-44b3969b693e.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Applied in AIDE's db server.

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed fixed in 2.8.0
