### ISSUE TITLE
Contact List - Update Button

### ISSUE THREAD

**Issue by ellaineronquillo** [rsx-labs/aide-frontend#180]
**Describe the bug**
For enhancement. Update button is always enabled even without changing any details.

**To Reproduce**
**Enhancement #1**
1. Go to 'Contact List'
2. Click on any registered name on 'Team Details' tab
3. Do not edit any of the details
4. Click 'Update' button

**Enhancement #2**
1. Go to 'Contact List'
2. Click on any registered name on 'Team Details' tab
3. Edit any of the details
4. Click 'Update' button

**Expected behavior**
**Enhancement #1**
If any of the details were not updated, the Update button should be disabled. The only option should be to close the window.

**Enhancement #2**
Update button should be enabled after changing any of the details, so as the close window.

**Version (please complete the following information):**
 - Version 2.6

**Comment by charissasylim** [comment]
Hold off on this enhancement. If we update this to disable the button if there are no changes, then all other screens should work the same for consistency.
