### ISSUE TITLE
Contact List - Labeling inconsistency

### ISSUE THREAD

**Issue by ellaineronquillo** [rsx-labs/aide-frontend#181]
**Describe the bug**
Button name is "Contacts List" but upon clicking the button, title name is "Contact List".

**To Reproduce**
1. Check the bottom panel, 'Contacts List'
2. Go to 'Contacts list'
3. Check the Title Name, 'Contact List'

**Expected behavior**
Labels should be matched and display "Contact List".

**Version (please complete the following information):**
 - Version 2.6

**Comment by jester0123** [comment]
Fixed. Ready for next build

**Comment by jester0123** [comment]
For QA testing 2.7 build

**Comment by ellaineronquillo** [comment]
Closed on Version 2.7.1
