### ISSUE TITLE
Label Correction - 3Cs  Display Page Number and Expand the image. 

### ISSUE THREAD

**Issue by vanchsalvador** [rsx-labs/aide-frontend#182]
**Describe the bug**
Expand the arrow image and display the page number

**To Reproduce**
1. Go to 3Cs Measure Page 
2. View the lower part of the page

**Comment by jhunellbarcenas** [comment]
@vanchsalvador This is a known issue we deployed it as is due to the complexity on how this module was written to apply our recent enhancement to display the page number.

**Comment by charissasylim** [comment]
To be fixed in future release

**Comment by ellaineronquillo** [comment]
The arrow button image was not expanded.
