### ISSUE TITLE
Contact List - Labeling inconsistency

### ISSUE THREAD

**Issue by ellaineronquillo** [rsx-labs/aide-frontend#183]
**Describe the bug**
Column displays "Extension" but upon clicking to update the contact details, title name is "Local Number".

**To Reproduce**
1. Go to 'Contact List'
2. Scroll to right and check the 'Extension' displayed
3. Click on any registered name on 'Team Details' tab
4. Go to 'Contact Details' tab
5. Check 'Local Number' displayed

**Expected behavior**
'Local Number' should be displayed on the column upon scrolling to right and upon updating the Contact Details.

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7 build

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by ellaineronquillo** [comment]
Closed on Version 2.7.1
