### ISSUE TITLE
Contact List - Reviewed column

### ISSUE THREAD

**Issue by ellaineronquillo** [rsx-labs/aide-frontend#184]
**Describe the bug**
For enhancement. "Reviewed" column should be "Review Date".

**To Reproduce**
1. Go to 'Contact List'
2. Scroll right to 'Reviewed'

**Expected behavior**
"Reviewed" column should be "Review Date".

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
@ellaineronquillo are you pertaining on the column wherein there is a checkbox? if yes, "Reviewed" is used just to know if it is already reviewed or not. It is not a date.

**Comment by charissasylim** [comment]
Closing this. Leave as is.
