### ISSUE TITLE
Announcement - Update button is not working no changes once pressed.

### ISSUE THREAD

**Issue by vanchsalvador** [rsx-labs/aide-frontend#185]
**Describe the bug**

Unable to Update the announcement data 

**To Reproduce**
1. Go to Home
2. Click one of the announcement displayed in Home Page 
3. Update the Data the press Update Button
4.  The added data was not included on the announcement update function is not working.

**Comment by jsanchez-cwt** [comment]
Fixed. Stored procedure executed on the server

**Comment by ellaineronquillo** [comment]
Closed 10/16/19
