### ISSUE TITLE
Announcement - Previous day announcement can no longer be displayed arrow page are not working

### ISSUE THREAD

**Issue by vanchsalvador** [rsx-labs/aide-frontend#186]
**Describe the bug**
Added 4 announcement today then the previous announcement data can no longer be seen on the screen 

**To Reproduce**
1. Go to Home
2. Add multiple announcement for today
3. Then View in Home Page 
4. Click the arrow pages 
5. Previous announcement can no longer be seen

**Comment by jhunellbarcenas** [comment]
@vanchsalvador @charissasylim This is due to btnNext and btnPrev is not working.
Fixed. Ready for v2.7 build

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by ellaineronquillo** [comment]
Closed 10/16/19
