### ISSUE TITLE
Announcement - Added 6 announcements today, but it only displays the first 4 items

### ISSUE THREAD

**Issue by vanchsalvador** [rsx-labs/aide-frontend#187]
**Describe the bug**
Added 6 announcements today, but it only displays the first 4 items

**To Reproduce**
1. Go to Home 
2. Click on Add image 
3. Add an announcement and check if the data was added 
4. Per checking the added new announcement was not displayed

**Comment by charissasylim** [comment]
@vanchsalvador There is page numbering below announcements, Didn't it work?

**Comment by charissasylim** [comment]
Similar to #186 thus to be covered there that page numbering buttons will be used to view other announcements.
Closing ticket.
