### ISSUE TITLE
Announcement - The latest announcement for today is placed on the last part  (data was arranged as ascending by date)

### ISSUE THREAD

**Issue by vanchsalvador** [rsx-labs/aide-frontend#188]
**Describe the bug**
Announcement - The latest announcement for today is placed on the last part  (data was arranged as ascending by date)

**To Reproduce**
1. Go to Announcement 
2. Click on Add Image 
3. Scroll down to the added data 
4. Per checking the latest added announcement is placed on the last part

**Comment by jhunellbarcenas** [comment]
@vanchsalvador Can you send a screenshot of this incident? As per checking into the SQL Script data was arranged descending by date. Also, upon recreating this incident newly added announcement is placed on the first part of the screen.

**Comment by jhunellbarcenas** [comment]
@vanchsalvador This could be just a conflict issue of button next page is not working.

**Comment by jhunellbarcenas** [comment]
@charissasylim  Can we close this?
