### ISSUE TITLE
Home -  Manage 3Cs graph font unreadable (font color should be black) 

### ISSUE THREAD

**Issue by vanchsalvador** [rsx-labs/aide-frontend#189]
**Describe the bug**
Unable to read the number displayed in the Manage 3Cs graph 

**To Reproduce**
1. Go to HomePage 
2. View the Manage 3Cs
3. Unable to read the number font color is white and the background of the page is white

**Comment by charissasylim** [comment]
Change font color to black instead of white

**Comment by ellaineronquillo** [comment]
Closed 10/16/19
