### ISSUE TITLE
Home - Time Clock is ANALOG, please remove this "Note: Hours is in military Time"

### ISSUE THREAD

**Issue by vanchsalvador** [rsx-labs/aide-frontend#190]
**Describe the bug**
The time clock is Analog even if I input a military  the display of the time is the same
suggest to put an AM and PM to display the exact time for comcell

**Comment by charissasylim** [comment]
Clock has been changed to text instead of analog.

**Comment by charissasylim** [comment]
Clock has been changed to text instead of analog in v2.7.1
