### ISSUE TITLE
[Resource Planner] August is displaying Aug 18 Sun column after Aug 30

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#191]
**Describe the bug**
Aug 18 is being displayed after Aug 30

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/63730149-90b8e300-c89c-11e9-85a3-9b1d373b037f.png)

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
@charissasylim This is because the code prioritizes to display all the dates that is Monday - Friday so any entry that is either Saturday or Sunday will always comes at the last part of the date. An enhancement on the sql script or on code i think would be the change if we are to fix this issue.

**Comment by charissasylim** [comment]
This is a bug and should be fixed.

**Comment by charissasylim** [comment]
Fixed in 2.7.1 by displaying all days of the month including weekends
