### ISSUE TITLE
Announcement - Add delete button in Announcement Module 

### ISSUE THREAD

**Issue by vanchsalvador** [rsx-labs/aide-frontend#192]
Request for Enhancement : 
If possible can we add a delete portions for the announcement in case the employee erroneously add an announcement

Version: 
2.6

**Comment by CelzGitHub** [comment]
Add Delete Functionality already push and ready for review.

**Comment by charissasylim** [comment]
@CelzGitHub can you please check-in code changes on or before November 15, 2019. Thanks,

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.2.0
