### ISSUE TITLE
Access - Remove the user on the list of member once logout to the system

### ISSUE THREAD

**Issue by vanchsalvador** [rsx-labs/aide-frontend#193]
Enhancement: 
The user already exit/close the application but still included on the list of member. Can this really happen? 

[Cha 8/27] Yes since the list is based on attendance for the day. Can you please add an enhancement instead so we can look into the possibility of  the user being removed once the user logs off.

Version: 2.6

**Comment by jhunellbarcenas** [comment]
@charissasylim @vanchsalvador Attendance dashboard is linked to the attendance module meaning if we try to have the employee be removed from the list i think this would require as another status for those employee who exit/close the application. (This is intended for the employees who go home right?)

@johnharveysanchez7 @jester0123 Do you have any suggestions/idea on another workaround for this one without requiring us to have another status?

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.2.0
