### ISSUE TITLE
Projects - Project field has a black drop down list 

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#194]
**Describe the bug**
When assigning a project to a specific employee, Project field has a black drop down list. Making it impossible to see if there is an available project that can be assigned.

**To Reproduce**
1. Go to 'Projects'
2. Click on 'Assign Projects'
3. Select an Employee
4. Click 'Assign' button
5. Click Project List drop down list

**Expected behavior**
Project List drop down list has all the available project that can be assigned to the employee

**Screenshots**
![Assign Project](https://user-images.githubusercontent.com/53286096/63747468-cf20c300-c8d9-11e9-9664-bc88f1d3d5e4.jpg)

V2.6

**Comment by jhunellbarcenas** [comment]
Same issue with #195 
Please see my comments on the discussion area.
