### ISSUE TITLE
Task - Selected employee is not highlighted

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#196]
**Describe the bug**
When assigning task to an employee, selected employee is not highlighted to be identified.

**To Reproduce**
1. Go to 'Task'
2. Select an employee to assign task

**Expected behavior**
Employee selected should be highlighted for easy identification.

**Screenshots**
![Task - Selected Employee](https://user-images.githubusercontent.com/53286096/63748706-6edf5080-c8dc-11e9-8a39-7364a0540b8a.jpg)

V2.6

**Comment by jhunellbarcenas** [comment]
@chloecastillo This feature only allows assignment of task for yourself. You cannot assign task to an employee even if you are a manager level user that is why selecting of employee is not highlighted and also because in the first place we are not selecting an employee here.

**Comment by jhunellbarcenas** [comment]
Can we close this? @chloecastillo @charissasylim
