### ISSUE TITLE
Improvements - List of Assignee is showing the Nickname of the employee when Action item is updated

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#197]
**Describe the bug**
When updating an existing Action Item, the employee name in the Assignee field is showing Nicknames of the employee.

**To Reproduce**
1. Go to 'Improvements'
2. Click on 'Action List'
3. Select an Action Item to update
4. Click on 'Select Employee' field

**Expected behavior**
'Select Employee' field should have the complete name of the employee. Same list should be seen when adding a new Action Item.

**Screenshots**
![Action List - Update](https://user-images.githubusercontent.com/53286096/63749339-ca5e0e00-c8dd-11e9-9fa0-c76b1004b497.jpg)

V2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7 build

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by ellaineronquillo** [comment]
Closed 10/16/19
