### ISSUE TITLE
Improvements - Removing the first assigned employee makes the application to close

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#198]
**Describe the bug**
When the first Assigned Employee is removed from the Action item, the application closes.

**To Reproduce**
1. Go to 'Improvements'
2. Click on 'Action List'
3. Select an Action item to update
4. Remove the first Assigned employee (This is when there are 2 or more assigned employees for the Action Item)

**Expected behavior**
Assigned employee should be removed.

**Screenshots**
![Improvements-ActionList Remove Assignee](https://user-images.githubusercontent.com/53286096/63749793-c54d8e80-c8de-11e9-9ba5-22a04e5f15a6.JPG)

V2.6

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7 build

**Comment by jhunellbarcenas** [comment]
NOTE: When removing an employee from the assignee make sure to select his/her name from the drop down list before clicking into the remove (-) button.

**Comment by jhunellbarcenas** [comment]
This issue is also happening in success registers update module

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for next build v2.8

**Comment by jhunellbarcenas** [comment]
Fixed also the same issue on success registers

**Comment by ellaineronquillo** [comment]
Closed 10/16/19
