### ISSUE TITLE
Allow transfer of asset between divisions

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#199]
**Is your feature request related to a problem? Please describe.**
Allow transfer of asset from one division to another (example from Dev to QA and vice versa)

**Comment by charissasylim** [comment]
@jhunellbarcenas can you discuss how this can be done to @IvanArtigo ?
Hoping we can get it done in version 2.9.0

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for next build.

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
