### ISSUE TITLE
Asset Assignment - Selecting an asset that is not assigned to you makes the application to close

### ISSUE THREAD

**Issue by jhunellbarcenas** [rsx-labs/aide-frontend#201]
**Describe the bug**

**To Reproduce**
1. Go to Assets
2. Click on Asset Assignment button
3. Navigate to All Assets
4. Search or click for an asset that is not assigned to you

![image](https://user-images.githubusercontent.com/39547140/63930069-3333ba80-ca85-11e9-99ff-2bcf684badcb.png)

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**

**Additional context**

**Comment by jester0123** [comment]
Fixed. Ready for next build.

**Comment by jester0123** [comment]
For QA testing. Build 2.7

**Comment by ellaineronquillo** [comment]
Closed 10/16/19
