### ISSUE TITLE
Improvements - display data according to date created

### ISSUE THREAD

**Issue by jhunellbarcenas** [rsx-labs/aide-frontend#203]
**Is your feature request related to a problem? Please describe.**
Ms. Arlene noticed that the latest item on this modules are on the last item of the table.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ellaineronquillo** [comment]
Not fixed.
Success Registers - The latest item on this module is not the first item.

![image](https://user-images.githubusercontent.com/54298100/66986009-95598500-f0f0-11e9-8f70-0e5cc2fc4476.png)

**Comment by charissasylim** [comment]
Fixed 2.9.0
