### ISSUE TITLE
Attendance Dashboard - Add a display order for status

### ISSUE THREAD

**Issue by jhunellbarcenas** [rsx-labs/aide-frontend#204]
Add a display order for status to organized viewing of employee's attendance.
Should be group by SL, VL, Onsite, and Present. Discussed with Ms. Cha regarding which status should comes first on the list.

**Comment by charissasylim** [comment]
Order should be Present, Onsite, VL, SL

**Comment by jhunellbarcenas** [comment]
Fixed. Applied the script change into AIDE DB Server

**Comment by ellaineronquillo** [comment]
Closed 10/17/19
