### ISSUE TITLE
Add Weekly Report - pressing backspace goes to create task

### ISSUE THREAD

**Issue by GiannCarlo** [rsx-labs/aide-frontend#206]
pressing backspace goes to create task UI

**To Reproduce**
1. Go to Billability
2. Click on Weekly Report
3. Click on Add Weekly report button
4. Select Incident type dropdown
5. Select one value (ex:bug)
6. Press Backspace on keyboard

**Expected Result**
The add weekly report UI will remain.

**Actual Result**
The screen will redirected to add tas UI.

![image](https://user-images.githubusercontent.com/28388078/64006146-4fe2f780-cb44-11e9-93f6-f654b5a1d1ff.png)

**Version (please complete the following information):**

**Additional context**

**Comment by chriscg** [comment]
Cannot reproduce in version 2.7.1.
