### ISSUE TITLE
[ASSET INVENTORY]: Unassign/Assign Flow Not Working Properly

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#208]
**Describe the bug**
1. Asset set to Partially Unassigned
2. Manager Approved and Asset Becomes Assigned (Should be Unassigned)
3. Manager updates asset as Unassigned and assign to Charissa 
4. Asset successfully updated as Unassigned but still assigned to Gliff (Should have assigned to Charissa)

Sample assets already approved.
SPEFY162385
SPEFY162385-A1
SPEFY162405
Sample assets for approval.
CCE0020484
CCE1600026
CCE0011753
CCE1600027
LVGDC180026
SPEFY162360-A11

**Version (please complete the following information):**
 - Version 2.6

**Additional context**

**Comment by charissasylim** [comment]
Unable to assign any asset to an employee

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.7 build

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Working in 2.7.1
