### ISSUE TITLE
UI for Metadata

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#213]
**Is your feature request related to a problem? Please describe.**
Add UI for meta-data creation for the benefit of departments with no developers
UI may not necessarily be within AIDE. It may be a separate tool.

Meta-data for the following tables that may need additional data during deployment.
1. ASSET_MANUFACTURER
2. ASSET_TYPE
3. DEPARTMENT
4. DIVISION
5. LEAVE-CREDITS

**Comment by cyberpau** [comment]
> 
> 
> **Is your feature request related to a problem? Please describe.**
> Add UI for meta-data creation for the benefit of departments with no developers
> UI may not necessarily be within AIDE. It may be a separate tool.
> 
> Meta-data for the following tables that may need additional data during deployment.
> 
>     1. ASSET_MANUFACTURER
> 
>     2. ASSET_TYPE
> 
>     3. DEPARTMENT
> 
>     4. DIVISION
> 
>     5. LEAVE-CREDITS

Hi Ma'am @charissasylim ,

I'm planning to create a separate tool (AIDE configuration tool) for this... for your approval. Thank you.

**Comment by charissasylim** [comment]
Please coordinate with Marvin about the tool since he is also making other tools to supplement aide

**Comment by trashvin** [comment]
@charissasylim , i already talked to @cyberpau and agreed that we cant go wrong with multiple tools :) and besides its all about learning by creating. we just need figure out later which tool is best for a certain task.
@rsx-labs/the-aide-team

**Comment by charissasylim** [comment]
@cyberpau looking forward to this one. Hoping this can be released sometime soon.

**Comment by charissasylim** [comment]
@cyberpau please include Skills Meta Data that associates per team and per department

**Comment by charissasylim** [comment]
@Michaelmical @trashvin  For implementation in kool-aide
Full List below that needs to be supported.
ASSET_MANUFACTURER
ASSET_TYPE
DEPARTMENT - already supported
DIVISION - already supported
LEAVE_CREDITS
SKILLS
STATUS
POSITION
PERMISSION GROUP
LOCATION

**Comment by trashvin** [comment]
Closing this one, it has been resolved in kool-aide
