### ISSUE TITLE
Skills - Remove GS DataMart and Shopko since we no longer support this product

### ISSUE THREAD

**Issue by jhunellbarcenas** [rsx-labs/aide-frontend#22]

**Comment by trashvin** [comment]
@jhunellbarcenas dont we have any field in the dbase that flags if the project is active or not? I think its much better if we have this field so that we dont delete past projects. Once this project opens again, we simply mark the project as active. 

cc : @rsx-labs/the-aide-team

**Comment by jhunellbarcenas** [comment]
@trashvin 

Currently we don't have a field for flag if the project is active or not on db same goes on the lists of skills. I'll have it configure this way po. Thanks for the idea! :)
