### ISSUE TITLE
Dashboard Revamp

### ISSUE THREAD

**Issue by chriscg** [rsx-labs/aide-frontend#225]
1. Move the following to dashboard mainscreen:
-> Move Team Commendations in 3rd column
-> Make Announcements in the middle
-> Put KPI Targets on the 1st column

2. Add new sub-menu buttons in Task:
-> Task Monitoring
-> Move Weekly Report here

3. Add new sub-menu buttons in Attendance:
-> Resoure Planning
-> Move Sick-Leave here
-> Move Vacation Leave here

4. Modify Billability to Productivity
5. Modify Productivity sub-menu buttons: retain Billable and Non-Billable hours only

6. Move Manage 3cs in right-side bar
7. Move Birthday in right-side bar at the middle
8. Resize CommCell clock

**Comment by chriscg** [comment]
Refer to https://github.com/rsx-labs/aide-frontend/commit/b3bca0eae94d7526d3255dd4b918848853f3f15b

**Comment by charissasylim** [comment]
@chriscg please close if completed
