### ISSUE TITLE
[KPI Summary] Add target KPI

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#229]
**Is your feature request related to a problem? Please describe.**
Is it possible to add actual target column after the KPI description? Or maybe add target as part of KPI column.

Is it possible to highlight in red the specific KPI if it falls under the target?

**Comment by chriscg** [comment]
See fix in https://github.com/rsx-labs/aide-frontend/issues/202

**Comment by charissasylim** [comment]
Confirmed Fixed on v2.8.0
