### ISSUE TITLE
[Reports] Monthly Asset Inventory Report

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#230]
**Is your feature request related to a problem? Please describe.**
Can we add a report generation also for monthly asset inventory to be submitted to MIS.
Details sent in email.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by trashvin** [comment]
The report is located at 
```
Server Location\AIDE Generated Reports\Asset Inventory
```
- The location is configurable. 
- The file name is configurable. -
- Format is excel, but you can generate a csv or json file. 
- Scheduling is done by the Windows Task Scheduler. The schedule is configurable. Currently, it is to generate the report every monday at 9:00PM
- The report can also be generation on demand
- More info coming in a separate repo. Soon.
