### ISSUE TITLE
[KPI Summary] Remove Month Dropdown and Replace Year to FY

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#231]
**Describe the bug**
1. Remove the Month dropdown since it is not applicable.
2. Year dropdown should work to show KPI for FY

**Version (please complete the following information):**
 - Version 2.7

**Comment by chriscg** [comment]
See fix in https://github.com/rsx-labs/aide-frontend/issues/202

**Comment by charissasylim** [comment]
Year drop down does not seem to work. Clicking 2018 does not clear the screen assuming there is no data for that year.

Also, need to update UI to display the full text.
![image](https://user-images.githubusercontent.com/52391236/66619423-7bf79b00-ec0f-11e9-93e1-37266614edb2.png)

**Comment by charissasylim** [comment]
Fixed 2.9.0
