### ISSUE TITLE
[Screen Consistency] Textfield label UI consistency

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#237]
**Describe the bug**
The following screens do not have the gray box with the field label unlike all the other screens.
1. Add/Update Contact List
2.  Add/Update Weekly Status Report
3. Add/Update Comm Cell Time

**Expected behavior**
UI should have consistent look and feel within one application

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/65302175-e0917e00-dbac-11e9-925a-4dbbc504ea79.png)

**Version (please complete the following information):**
 - Version 2.7.1

**Comment by charissasylim** [comment]
Changes not applied yet on the Add Contact screen.

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
