### ISSUE TITLE
[Others - Tracker] Received this message "Arithmethic operation resulted in an overflow." once tracker button is pressed

### ISSUE THREAD

**Issue by vanchsalvador** [rsx-labs/aide-frontend#238]
**Describe the bug**
A prompt message received "Arithmethic operation resulted in an overflow."  once tracker button is pressed.

**To Reproduce**
1. Go to Others 
2. Click on Tracker
3. See error

 - Version [2.7.1]

**Comment by ellaineronquillo** [comment]
Not fixed.
