### ISSUE TITLE
[Others - Comm. Cell Meeting] Unable to create/add facilitator and minutes taker. Not working

### ISSUE THREAD

**Issue by vanchsalvador** [rsx-labs/aide-frontend#239]
**Describe the bug**
Unable to create/add facilitator and minutes taker. Create button not working. 

**To Reproduce**
1. Go to Others 
2. Click on Comm Cell Meeting 
3. Add/Create Facilitator and Minutes Taker
4. Does not reflect on the module

Version: 2.7.1

**Comment by chriscg** [comment]
Cannot reproduce in latest codes and DB.

@vanchsalvador, did you install the latest database scripts because we have added new columns for some tables and adjusted some stored procedures?

**Comment by charissasylim** [comment]
Can you please check her machine as she is getting errors that I don’t see in my machine also. Just so we prevent more incidents like this. Thanks!

**Comment by vanchsalvador** [comment]
also encounter in Ellaine's Machine. Please check if need to re-install the application again.

**Comment by chriscg** [comment]
This is caused by invalid data in COMCELL_MEETING table where facilitator and minutes_taker should be employee ID and not nick name or first name.
