### ISSUE TITLE
[Projects- Create] Encoded Details for the project does not reflect on the module. Not Working.

### ISSUE THREAD

**Issue by vanchsalvador** [rsx-labs/aide-frontend#240]
**Describe the bug**
Prompted that I already added a project but does not reflect on the module.

**To Reproduce**
1. Go to Projects 
2. Click Create
3. Prompted that new projects is already added but does not reflect on the module.

Version: 2.7.1

**Comment by ellaineronquillo** [comment]
Closed 10/16/19
