### ISSUE TITLE
[Team Commendation] Unable to add/create details, one of the required field is the project code currently projects module is not working.

### ISSUE THREAD

**Issue by vanchsalvador** [rsx-labs/aide-frontend#241]
**Describe the bug**
Unable to add/create details, one of the required field is the project code currently Project module is not working.

**To Reproduce**
1. Go to Dashboard 
2. Click on Team Commendation (+) 
3. Create  Commendation 
4. Unable to create (project code - not available/empty) - one of the required field

 - Version 2.7.1

**Comment by chriscg** [comment]
Cannot reproduce in latest codes and DB.

@vanchsalvador, did you install the latest database scripts because we have added new columns for some tables and adjusted some stored procedures?

**Comment by vanchsalvador** [comment]
installation of the latest database scripts is not included in the instruction do we need to re-install the application again? note that this is also being encounter by Ellaine.

**Comment by chriscg** [comment]
This should be okay once https://github.com/rsx-labs/aide-frontend/issues/240 is fixed.

**Comment by ellaineronquillo** [comment]
Closed  10/16/19
