### ISSUE TITLE
[Comm Cell Time] Change Prompt Message for invalid input of hours from 24 to 12. 

### ISSUE THREAD

**Issue by vanchsalvador** [rsx-labs/aide-frontend#242]
**Describe the bug**
Encoded 13 hours and 00 minutes 
Prompted: Please check time entry. Hours input should not exceed to 24. Minutes input should not exceed to 59.
Correction: Please check your time entry. Input hours should not exceed to 12 and Input Minutes should not exceed to 59.

- Version 2.7.1

**Comment by ellaineronquillo** [comment]
Closed 10/17/19
