### ISSUE TITLE
[Assign Project] - cannot assign more than 1 resource to a project

### ISSUE THREAD

**Issue by chriscg** [rsx-labs/aide-frontend#246]
**Describe the bug**
cannot assign more than 1 resource to a project

**To Reproduce**
1. Go Projects
2. Click on Assign Projects
3. Assign at least to employees to a project
4. only one employee can be assigned

**Expected behavior**
Can assign more than 1 employee to a project

**Screenshots**

**Version (please complete the following information):**

**Additional context**

**Comment by charissasylim** [comment]
Confirmed fixed in 2.8.0
