### ISSUE TITLE
[Late Tracking] Header shows the wrong month

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#253]
**Describe the bug**
The header 'Late For the Month of [month]' shows the wrong month when there is a dropdown month value being selected.
E.g. Oct 1 shows 'Late for the Month of October' even if dropdown and bar graph shows September data

Check if :ate for the Fiscal Year functionality also works the same.

Change also 'For' to lowercase 'for'

**To Reproduce**
1. Go to 'Late Tracking'
2. Select a month
3. Label still shows current month

**Expected behavior**
Label should show month selected in the dropdown

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/65925977-8fdc1980-e425-11e9-8c66-7c241a565a05.png)
![image](https://user-images.githubusercontent.com/52391236/65926071-f06b5680-e425-11e9-9d8a-e84024cd06e5.png)

**Version (please complete the following information):**
 - Version 2.7.1

**Comment by jester0123** [comment]
Ready for next build

**Comment by charissasylim** [comment]
Confirmed Fixed in 2.8
