### ISSUE TITLE
[Access] "Failure Sending Mail" pop-up notification appears

### ISSUE THREAD

**Issue by ellaineronquillo** [rsx-labs/aide-frontend#256]
**Describe the bug**
"Failure Sending Mail" pop-up notification appears

**To Reproduce**
Precondition: Outlook is NOT Running 
1. In Email Verification Window input <personal email> then click "Send" button. An Access Code window appeared. 
2. Close the Access Code window by pressing "OK" button
or by pressing [x] on the upper right of the window

**Expected behavior**
There should be no prompt window for Failure Sending Mail

**Screenshots**
![image](https://user-images.githubusercontent.com/54298100/65937112-5f11d980-e451-11e9-825b-cfc22c22dd23.png)

**Version**
 - Version [2.7.1]

**Comment by charissasylim** [comment]
@jester0123 Comment out the sending of email message while the feature is not yet available.

**Comment by charissasylim** [comment]
@jester0123  is this ready for build?

**Comment by jhunellbarcenas** [comment]
Fixed. AIDE now successfully sends email

**Comment by jhunellbarcenas** [comment]
Failure sending mail using external emails. 
Error code: mailbox unable the server response was 5.7.1

**Comment by jhunellbarcenas** [comment]
As per sir marvin email exchange server is not the issue as he successfully tested sending email using phyton language. There must be something wrong with the code or issue that's why it fails sending emails to external domain.

**Comment by charissasylim** [comment]
@trashvin @chriscg Can we remove the OTP functionality and use Erell's suggestion instead or would his suggestion not work?
1. System can alternatively get the Username in case email (outlook) not working as raised on our meeting. I guess logon user maybe a good alternative. --> SystemInformation.UserName

**Comment by charissasylim** [comment]
tested and working in 3.3.5
