### ISSUE TITLE
[Home] Cannot delete the displayed text for all search bars

### ISSUE THREAD

**Issue by ellaineronquillo** [rsx-labs/aide-frontend#259]
**Describe the bug**
Cannot delete the displayed text for all search button

**To Reproduce**
1. Input data on all Search bars

**Expected behavior**
Displayed text should be deleted once data is inputted

**Screenshots**
![image](https://user-images.githubusercontent.com/54298100/65938219-fb89ab00-e454-11e9-8d99-2b930e1b0aa7.png)

![image](https://user-images.githubusercontent.com/54298100/65938225-fd536e80-e454-11e9-8a90-c68e525972ec.png)

**Version**
 - Version [2.7.1]

**Comment by vanchsalvador** [comment]
@charissasylim would like to ask what is the question for this ticket? Thank you

**Comment by charissasylim** [comment]
@vanchsalvador @ellaineronquillo 
Displayed text disappears once a value is typed in.  
If this is the scenario you meant then this is WAD.

![image](https://user-images.githubusercontent.com/52391236/66032417-efc2e500-e537-11e9-8931-11cef76f6f3f.png)

![image](https://user-images.githubusercontent.com/52391236/66032464-ff422e00-e537-11e9-8c59-d1eac89d9b93.png)
