### ISSUE TITLE
[Comm Cell Reminder] Incorrect Alarm Time

### ISSUE THREAD

**Issue by ellaineronquillo** [rsx-labs/aide-frontend#260]
**Describe the bug**
Incorrect Alarm Time on Comm Cell Reminder

**To Reproduce**
1. Set a specific time for Comm Cell
2. Wait for the alarm reminder

EX:
Meeting is set : 12PM - Alarm @2PM
Meeting is set : 10:15AM - Alarm @10:02AM

**Expected behavior**
Alarm reminder should be based on the Comm Cell Time

**Screenshots**
![image](https://user-images.githubusercontent.com/54298100/65938807-a64e9900-e456-11e9-8bdb-c5b227a96482.png)

![image](https://user-images.githubusercontent.com/54298100/65938810-a8185c80-e456-11e9-9e8a-439d5080857a.png)

**Version**
 - Version [2.7.1]

**Comment by GiannCarlo** [comment]
Fixed. Ready for next build
