### ISSUE TITLE
[Home] Update Comm. Cell window still displays after updating the comm cell time

### ISSUE THREAD

**Issue by ellaineronquillo** [rsx-labs/aide-frontend#261]
**Describe the bug**
Update Comm. Cell window still displays after updating the comm cell time

**To Reproduce**
[1] Click (+) on "Comm. Cell Time"
[2] Fill up the Day, Hours and Minutes. Click "Update" button
[3] Click "OK"

**Expected behavior**
Update Comm. Cell window should be closed after updating

**Screenshots**
![image](https://user-images.githubusercontent.com/54298100/65939398-68eb0b00-e458-11e9-9a6b-cb93d66fd038.png)

**Version**
 - Version [2.7.1]

**Comment by charissasylim** [comment]
@ellaineronquillo @vanchsalvador was there an update successfully message?

**Comment by vanchsalvador** [comment]
@charissasylim , there is a prompt message window "Successfully set new Comm. Cell clock." with "OK" button. Once "OK" button it will not automatically close, the user needs to click on [x] to be able to do so but after that the dashboard is no longer accessible.

**Comment by vanchsalvador** [comment]
@charissasylim , there is a prompt message window "Successfully set new Comm. Cell clock." with "OK" button. Once "OK" button it will not automatically close, the user needs to click on [x] to be able to do so

**Comment by charissasylim** [comment]
Fixed 2.9.0
