### ISSUE TITLE
[Home] Not all of the lessons learnt are displayed

### ISSUE THREAD

**Issue by ellaineronquillo** [rsx-labs/aide-frontend#263]
**Describe the bug**
Not all of the lessons learnt are displayed before searching. All the lessons learnt are displayed after deleting an entry on "Search Lessons Learnt"

**To Reproduce**
[1] From Home / Dashboard, click the "Manage 3C"
[2] Click "Lessons Learnt" button on the upper panel
[3] Input detail/s on "Search Lessons Learnt" to search a specific lessons learnt
[4] Delete entry on "Search Lessons Learnt"

**Expected behavior**
All the lessons learnt should be displayed before searching for a specific information

**Screenshots**
![image](https://user-images.githubusercontent.com/54298100/65939624-01818b00-e459-11e9-98d2-898a6969ea09.png)

![image](https://user-images.githubusercontent.com/54298100/65939628-047c7b80-e459-11e9-96d7-f00d982382b6.png)

**Version**
 - Version [2.7.1]

**Comment by charissasylim** [comment]
@ellaineronquillo @vanchsalvador Only QA data should be displayed. 
How did you get the 2nd screenshot?

**Comment by vanchsalvador** [comment]
@charissasylim the next screenshot was displayed after deleting any encoded data on the search field.
for example: On search field > Input: abcd then delete the encoded data it will display all the lesson learnt encoded information.

**Comment by vanchsalvador** [comment]
@charissasylim the next screenshot was displayed after deleting any encoded data on the search field.
for example: On search field > Input: abcd then delete the encoded data it will display all the other lesson learnt information.

**Comment by charissasylim** [comment]
@johnharveysanchez7 Boni tried to add lessons learnt yesterday 10/15. Message shows successful but I don't see it saved in the database.

**Comment by charissasylim** [comment]
duplicate
