### ISSUE TITLE
[Task] Unable to add "Task"

### ISSUE THREAD

**Issue by ellaineronquillo** [rsx-labs/aide-frontend#267]
**Describe the bug**
Unable to add "Task". Select a project dropdown is empty

**To Reproduce**
[1] From Home / Dashboard, click the "Task" on the bottom panel
[2] Click the (+) button to add task
[3] Fill up the required fields then click "Create" button

**Expected behavior**
Should be able to add Task

**Screenshots**
![image](https://user-images.githubusercontent.com/54298100/65942469-ee25ee00-e45f-11e9-8078-81740fa19342.png)

**Version**
 - Version [2.7.1]

**Comment by jhunellbarcenas** [comment]
Fixed. This issue is due to create project issue.

**Comment by ellaineronquillo** [comment]
Closed 10/16/19
