### ISSUE TITLE
[Productivity] KPI Summary for 2018 is not displayed

### ISSUE THREAD

**Issue by ellaineronquillo** [rsx-labs/aide-frontend#270]
**Describe the bug**
KPI Summary for 2018 is not displayed. Labeling and graphs are also not changed

**To Reproduce**
[1] From Home / Dashboard, click the "Productivity" on the bottom panel
[2] Click "KPI Summary" button on the upper panel
[3] Select year 2018
[4] Check the labeling and the graphs

**Expected behavior**
Even there is no KPI Target, the labeling should be changed to "Monthly KPI Summary for FY 2018" and the graph should be empty

**Screenshots**
![image](https://user-images.githubusercontent.com/54298100/65943056-2b3eb000-e461-11e9-8568-495068ba42f0.png)

**Version (please complete the following information):**
 - Version [2.7.1]

**Comment by charissasylim** [comment]
@chriscg did you fix the dropdown in the KPI Summary already for the next build?

**Comment by charissasylim** [comment]
duplicate of #231

**Comment by charissasylim** [comment]
Fixed 2.9.0
