### ISSUE TITLE
[Skills] Incorrect pop-up message

### ISSUE THREAD

**Issue by ellaineronquillo** [rsx-labs/aide-frontend#271]
**Describe the bug**
Incorrect pop-up message: "You are going to update your Skills do you wish to continue?"

**To Reproduce**
[1] From Home / Dashboard, click the "Skills" on the bottom panel
[2] Double-click an employee's name
[3] All entry fields should be empty then lick "Update" button

**Expected behavior**
The pop-up notification should be an error message stating that the List of Skills to update is empty then will go back to list of skills display

**Screenshots**
![image](https://user-images.githubusercontent.com/54298100/65943149-6345f300-e461-11e9-94c0-4e54edf1154d.png)

**Version**
 - Version [2.7.1]

**Comment by jhunellbarcenas** [comment]
This is not a bug because even though you did not update a skill date reviewed is actually updated here. Date reviewed is used to determine list of employees who did not update their skills as part of KRA

**Comment by charissasylim** [comment]
@jhunellbarcenas when does this message appear? i don't see it when clicking an employee.

**Comment by charissasylim** [comment]
WAD
