### ISSUE TITLE
[Skills] All employees and their skills is displayed even the data is not updated

### ISSUE THREAD

**Issue by ellaineronquillo** [rsx-labs/aide-frontend#272]
**Describe the bug**

**To Reproduce**
[1] From Home / Dashboard, click the "Skills" on the bottom panel
[2] Double-click an employee's name
[3] All entry fields should be empty then lick "Update" button
[4] Click "No"
[5] Click "Update" button
[6] Click "Yes"

**Expected behavior**
Should go back to list of skills display. The update button and skills rating radio button should not be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/54298100/65943338-d18ab580-e461-11e9-9633-217a3af4358f.png)

**Version**
 - Version [2.7.1]

**Comment by jhunellbarcenas** [comment]
Change would be is to hide the controls for update whenever returned to view all employees skills page

**Comment by charissasylim** [comment]
@ellaineronquillo @vanchsalvador when should this 'Should go back to list of skills display.' happen?
And when should this 'The update button and skills rating radio button should not be displayed' happen?

**Comment by charissasylim** [comment]
WAD. Should not hide controls in view all since that is the legend for the screen.
Clicking update button updates the review date even if there is no update on the skill level.

**Comment by jhunellbarcenas** [comment]
Last Reviewed and list of skills controls are still displayed after an update. It should not be displayed.
