### ISSUE TITLE
[Projects] Created project is not displayed

### ISSUE THREAD

**Issue by ellaineronquillo** [rsx-labs/aide-frontend#273]
**Describe the bug**
Created project is not displayed

**To Reproduce**
[1] From Home / Dashboard, click the "Projects" on the bottom panel
[2] Fill up the required fields then click "Clear" button
[3] Fill up the required fields then click "Create" button

**Expected behavior**
Created Project should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/54298100/65945636-f9c8e300-e466-11e9-9bea-85878a010b34.png)

**Version**
 - Version [2.7.1]

**Comment by jhunellbarcenas** [comment]
Fixed. Database issue proj_id column should be int identity datatype

**Comment by ellaineronquillo** [comment]
Closed 10/16/19
