### ISSUE TITLE
[Late Tracking] Mark as Late only if time in is 10:01 onwards

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#276]
**Describe the bug**
Tardy starts 10:01. 10:00:33 is not considered tardy by Sunfish.

**Version (please complete the following information):**
 - Version 2.7.1

**Comment by ellaineronquillo** [comment]
Incorrect time was logged in to AIDE.
Time Set = 10:00 AM

![image](https://user-images.githubusercontent.com/54298100/66991474-ba52f580-f0fa-11e9-831f-8cec44d34ef5.png)

![image](https://user-images.githubusercontent.com/54298100/66991490-c2129a00-f0fa-11e9-8a7d-e83cd4ff32c0.png)
