### ISSUE TITLE
[Attendance] Employee Pictures Not Displaying in AIDE TV and while on FAI VPN

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#282]
**Describe the bug**
Employee Pictures not displaying in AIDE TV and while on FAI VPN

AIDE TV Laptop on workgroup domain
AIDE VM on Primergy Server on workgroup domain
Primergy Server on CORP domain
Employee Laptops on CORP domain

**Version (please complete the following information):**
 - Version 2.7.1

**Comment by trashvin** [comment]
Verified working on FAI VPN, image are displaying. Will concentrate on the TV display issue.

**Comment by charissasylim** [comment]
Per Marvin, TV display issue is related to permission on folder.

**Comment by jhunellbarcenas** [comment]
Fixed. Just needed to open the employee photos folder to input primergy server credentials.
