### ISSUE TITLE
[Resource Planner] Half-day leave showing as Present in Resource Planner

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#285]
**Describe the bug**
Half-day leave showing as Present in Resource Planner instead of the half day leave

**To Reproduce**
1. Add HEL to an employee. HEL is shown in Resource planner.
Note: Resource Planner record was added directly in DB due to error unable to add via AIDE
2. Employee logs in on the other half of the day.
3. Resource planner shows P instead of HEL

**Expected behavior**
HEL or HSL or HVL should still be displayed in Resource Planner.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/66529273-6c0b8880-eb35-11e9-829b-c81df247a62c.png)

DB shows HEL is recorded.
![image](https://user-images.githubusercontent.com/52391236/66529326-9bba9080-eb35-11e9-8739-d7b8d00e8109.png)

**Version (please complete the following information):**
 - Version 2.7.1

**Comment by charissasylim** [comment]
In older AIDE versions, ATTENDANCE.status is equal to RESOURCE_PLANNER.status.
So if RESOURCE_PLANNER is HSL status of 5 then ATTENDANCE also stores HSL status of 5.

**Comment by GiannCarlo** [comment]
included fix of [Attendance] Allow different leaves in the morning and in the afternoon #304

**Comment by GiannCarlo** [comment]
Sample Result : 
![image](https://user-images.githubusercontent.com/28388078/68572177-bae36f80-049f-11ea-9a17-ba964a07c5b6.png)
Also fixed Attendance status will set automatic for respective status of employee.

**Comment by charissasylim** [comment]
Fixed 2.9.0
