### ISSUE TITLE
[Improvements] Name of the removed assigned employee still displays

### ISSUE THREAD

**Issue by ellaineronquillo** [rsx-labs/aide-frontend#296]
**Describe the bug**
Name of the removed assigned employee still displays

**To Reproduce**
[1] Go to 'Improvements'
[2] Click on 'Action List'
[3] Select an Action item to update
[4] Remove the one Assigned employee (This is when there are 2 or more assigned employees for the Action Item)

**Expected behavior**
Name of the removed assigned employee name should not be displayed / should be removed

**Screenshots**
![image](https://user-images.githubusercontent.com/54298100/66903464-1e12eb00-f035-11e9-9932-5fcf8e1172f9.png)

**Version**
 - Version [2.8.0]

**Comment by jhunellbarcenas** [comment]
I've already made a fix regarding this one might have just missed to change the labels. This is already working on the current version.

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
