### ISSUE TITLE
[Projects] - was able to add a project with project code that starts with zero but does not reflect on the list of added projects

### ISSUE THREAD

**Issue by vanchsalvador** [rsx-labs/aide-frontend#298]
**Describe the bug**
Added Projects with project code that starts with zero does not reflect on the list of projects

**To Reproduce**
Go to Project Module and input the following: 
Input Code:  00011001
Project Description: Project External - 00011001
Category: Project 
Billability: External 

Prompted "Project successfully added" with ok button
View the List of Projects > the encoded project does not reflect on the table 

Version:  2.8

**Comment by GiannCarlo** [comment]
Fixed. Ready for next build

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
