### ISSUE TITLE
[Commendation] Unable to save full commendation details

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#300]
**Describe the bug**
Unable to save all the details in the commendation.

**Screenshots**

Inputted data
![image](https://user-images.githubusercontent.com/52391236/67909625-d5256f80-fbba-11e9-9176-ad1e30ccd86c.png)

Saved data
![image](https://user-images.githubusercontent.com/52391236/67909592-b7f0a100-fbba-11e9-89aa-75765f16dc8e.png)

**Version (please complete the following information):**
 - Version 2.8

**Comment by charissasylim** [comment]
@chriscg Not fixed in 2.9.0

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
