### ISSUE TITLE
[Attendance] Allow different leaves in the morning and in the afternoon

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#304]
**Describe the bug**
What if the employee is on SL in the morning and EL in the afternoon?
Currently, AIDE records it as HSL count value = 1 in RESOURCE_PLANNER.
RESOURCE_PLANNER PKs are EMP_ID, DATE_ENTRY, STATUS. Given that, it should be possible to have 2 records for this scenario then.
Row 1  with Status of HSL
Row 2 with Status of HEL

Can both be displayed on screen also?

**To Reproduce**
1. Add HSL on Employee 1
2. Add HEL on the same Employee 1 on the same date as #1
3. Check database

**Version (please complete the following information):**
 - Version 2.8.0

**Comment by GiannCarlo** [comment]
included fix of [Resource Planner] Half-day leave showing as Present in Resource Planner #285

**Comment by GiannCarlo** [comment]
Sample Result : 
![image](https://user-images.githubusercontent.com/28388078/68572281-fd0cb100-049f-11ea-953e-0bcd0ffcf679.png)

Also fixed Attendance status will set automatic for respective status of employee.

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
