### ISSUE TITLE
[Resource Planner] Manage Leaves button color looks disabled

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#314]
**Describe the bug**
Button color for Manage Leaves should not be grey.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/69389535-4e6e3900-0d07-11ea-9d50-980787e82f57.png)

**Version (please complete the following information):**
 - Version 2.8

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
