### ISSUE TITLE
[Resource Planner] Cancel leave button does not cancel the leave

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#315]
**Describe the bug**
Cancel leave button does not cancel the leave

**To Reproduce**
1. Go to Resource Planner - Manage Leaves
2. Click on the cancel button for one of your leaves
3. Success message is displayed but leave remains present instead of cancelled.

**Version (please complete the following information):**
 - Version 2.8

**Comment by charissasylim** [comment]
@jester0123 is this ready for 3.0.0 build or 2.9.0?

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
