### ISSUE TITLE
[Inventory - Assets] Inventory formerly assigned to resigned employees is not searcheable

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#325]
**Describe the bug**
Inventory currently unassigned (assigned to Cha since spare) but formerly assigned to resigned employee is not searchable in Assets. 

**To Reproduce**
1. Go to Assets.
2. Input CCE1600039 in search asset
3. No search result

**Expected behavior**
Expected to be searchable since status is unassigned.
Can you please check query if this is bec employee status is also checked?
If an employee is not resigned, an asset is searchable.

**Version (please complete the following information):**
 - Version 2.9

**Comment by jhunellbarcenas** [comment]
Fixed by recent changes made by @GiannCarlo

**Comment by charissasylim** [comment]
Fixed 2.9.0
