### ISSUE TITLE
[Comm Cell Time] No Alarm Showing Up

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#326]
**Describe the bug**
No Alarm Showing Up

**Version (please complete the following information):**
 - Version 2.9.0

**Comment by GiannCarlo** [comment]
Fixed.

**Comment by jhunellbarcenas** [comment]
Please test further @GiannCarlo

**Comment by GiannCarlo** [comment]
Fixed. Ready for next build. Reviewed by Jhunell

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.1
