### ISSUE TITLE
[Resource Planner] Unable to view January 2019-2020 leaves

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#327]
**Describe the bug**
An error 'An item with the same key has already been added' when viewing January 2019-2020 records after adding January 2, 2020 leave. Maybe it is confused if to display 2019 or 2020? But I don't see a January 2, 2019 record in the Resource Planner / Attendance tables.

**To Reproduce**
1. Input January 2, 2020 VL
2. Go to Resource Planner and select January 2019 - 2020
3. Error message 'An item with the same key has already been added' is displayed. No records displayed.

**Expected behavior**
Display January 2020 records.

**Screenshots**

**Version (please complete the following information):**
 - Version 2.9.0

**Comment by GiannCarlo** [comment]
Fixed

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
