### ISSUE TITLE
[All screens with FY Dropdown] FY dropdown should contain past, present, future FY

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#328]
**Is your feature request related to a problem? Please describe.**
All FY dropdowns should contain past FY, current FY, and next FY.
Ex. FY2018-2019, FY2019-2020, FY 2020-2021

**Describe the solution you'd like**
Code behind should automatically compute and should not be hard-coded to avoid doing code change every year.
If possible, there should only be 1 function to be used by all screens.

Screens affected:
1. Team Commendations
2. Attendance - Resource Planner, Sick Leave, Vacation Leave
3. Task - Weekly Report
4. Productivity - Billable Hours, Non-Billable Hours (change to FY range like other screens), KPI Summary (change to FY range like other screens)
5. Others - Comm Cell Meeting, Late Tracking

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
