### ISSUE TITLE
[Success Register] Update button is has different font size

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#334]
**Describe the bug**
Update button in Update Success Register screen has a different font size compared to all other buttons.

**To Reproduce**
1. Go to Improvements - Success Registers
2. Click on a success register to edit.
4. See UPDATE button

**Expected behavior**
Button should be same style as all other buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/69780716-f774d200-11e6-11ea-8cf3-22eb0e03b934.png)

**Version (please complete the following information):**
 - Version 2.9.0

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
