### ISSUE TITLE
[Resource Planner] Star on Employee Name for Perfect Attendance AND No Tardy for the Month

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#338]
**Describe the solution you'd like**
Can we put a star beside the name of the employee who has Perfect Attendance with No Tardy for the month? This will get displayed once the full month has been completed. So if current month is Dec, previous months should have the star display for those with perfect attendance with no tardy.

![image](https://user-images.githubusercontent.com/52391236/70102773-1f938380-1674-11ea-94ef-fbb8ed6103a9.png)

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.1
