### ISSUE TITLE
[Team Commendation] Month and Year Dropdown does not display default current month and year

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#339]
**Describe the bug**
1. Team Commendation month and year dropdown does not display current month and year by default.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/70103294-b1e85700-1675-11ea-90bb-fa754396b7e6.png)

**Version (please complete the following information):**
 - Version 2.9.0

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
