### ISSUE TITLE
[Weekly Report] Adjust button width a little bit more

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#340]
**Describe the bug**
Adjust View Team Status Report button width a little bit more.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/70103388-01c71e00-1676-11ea-989b-7b765c4a95d0.png)

**Version (please complete the following information):**
 - Version 2.9.0

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
