### ISSUE TITLE
[3C] Page 1 of n display is occupying 2 lines

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#343]
**Describe the bug**
Page 1 of n display is occupying 2 lines. Adjust display width.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/70104017-bd3c8200-1677-11ea-815d-07ebcd6ff2d9.png)

**Version (please complete the following information):**
 - Version 2.9.0

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
