### ISSUE TITLE
[Skills Matrix] Label Could Deliver Unsupported is truncated

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#344]
**Describe the bug**
'Could Deliver Unsupported' is truncated in the display. Increase display width.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/70104704-d34b4200-1679-11ea-8082-b4a80ac6752f.png)

**Version (please complete the following information):**
 - Version 2.9.0

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
