### ISSUE TITLE
[Improvements] Dashed box is not fully displayed

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#360]
**Describe the bug**
See sample screenshot.
Applies to the following screens -
1. Add 3C
2. Update 3C
3. Update Action List
4. Add Lessons Learnt

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/70286197-3ae1c880-1805-11ea-9f68-18d51f9a426f.png)

**Version (please complete the following information):**
 - Version 2.9.0

**Comment by jester0123** [comment]
@charissasylim 
Dashed boxes has been removed due to design discrepancies while running in lower resolution. 

This will look like this one now.
![image](https://user-images.githubusercontent.com/50006196/70400625-d0c85e00-1a66-11ea-96e6-26a88720ff3e.png)

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
