### ISSUE TITLE
[Asset Assignment] Allows blank employee ID to be assigned an asset

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#368]
**Describe the bug**
Assign Asset allows blank employee ID.

**To Reproduce**
1. Go to Asset Assignment - All Asset
2. Click on an Unassigned Asset. By default, Assigned To has a manager's name value.
3. Select Status to be Assigned
4. The Assigned To field is still populated. This should be cleared as it allows employee ID to be submitted as blank. 

**Expected behavior**
Assigned To field should be cleared when Status 'Assigned' is selected.
Should not allow submission without required fields duly filled up.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/70412562-0897cb80-1a90-11ea-8eca-747e8486557d.png)

**Version (please complete the following information):**
 - Version 2.9.0

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for next build

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
