### ISSUE TITLE
[Tracker] Remove extra screen space on Add Tracker

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#373]
**Describe the bug**
Remove extra space on Add Tracker.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/70589428-a6afa100-1c0a-11ea-9ca6-e2de5651d7db.png)

**Version (please complete the following information):**
 - Version 2.9.0

**Comment by jester0123** [comment]
@charissasylim 

Already been fixed at latest source.

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
