### ISSUE TITLE
[Tracker] Adjust completed date textbox height

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#374]
**Describe the bug**
Adjust completed date textbox height so that the value does not get covered by gray label

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/70589629-1faef880-1c0b-11ea-994d-7efb74b6141a.png)

**Version (please complete the following information):**
 - Version 2.9.0

**Comment by jester0123** [comment]
@charissasylim 
reduce the font size of description instead of changing the size of textbox to make it similar to other screens. 

![12162019](https://user-images.githubusercontent.com/50006196/70874623-f1a42c80-1fed-11ea-8bbf-0306bed0586e.PNG)

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
