### ISSUE TITLE
[Home Manage 3C] Can the circular graph have the same look as that from Tracker

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#375]
**Describe the bug**
Can the circular graph have the same look as that from Tracker

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/70589692-4e2cd380-1c0b-11ea-8b8e-1af219fe08ee.png)

**Version (please complete the following information):**
 - Version 2.9.0

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
