### ISSUE TITLE
[Task] Add scroll bar in case not all 5 employees listed fit in the screen

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#389]
**Describe the bug**
 Add scroll bar in case not all 5 employees listed fit in the screen

**Version (please complete the following information):**
 - Version 2.9.0

**Comment by GiannCarlo** [comment]
Fixed. Ready for Next Build. Reviewed by Harvey and Jester 
sample Output :
if has 5 employees that is not fit in the screen : 
![image](https://user-images.githubusercontent.com/28388078/71800022-e181e900-3091-11ea-9558-222ffbc6064c.png)

and if all 5 employees are fit : 
![image](https://user-images.githubusercontent.com/28388078/71800044-f5c5e600-3091-11ea-89cf-222f06d84a23.png)

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.1
