### ISSUE TITLE
[KPI Summary] AIDE Crash when double-clicking on empty KPI cell

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#391]
**Describe the bug**
Added KPI 1 for the month
KPI 2 is still empty
Clicking on KPI 2 cell causes AIDE to crash

**To Reproduce**
1. Go to Productivity - KPI Summary
2. Add a KPI entry
3. Click on a empty KPI cell
4. AIDE crashes

**Expected behavior**
Should not allow clicking on empty cell since there is nothing to edit

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/71701608-8cca3e00-2e05-11ea-89d1-07749566ef79.png)

**Version (please complete the following information):**
 - Version 3.0

**Comment by GiannCarlo** [comment]
Reviewed by Jester and harvey

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.1
