### ISSUE TITLE
[Comm Cell Meeting] Object Reference error when clicking Comm Cell Meeting Menu

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#392]
**Describe the bug**
Object Reference error when clicking Comm Cell Meeting Menu

**To Reproduce**
1. Click Comm Cell Meeting Menu
2. Object Reference error pops up

**Expected behavior**
No error should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/71701733-46291380-2e06-11ea-8f86-aa8f8f422638.png)

**Version (please complete the following information):**
 - Version 3.0

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.1
