### ISSUE TITLE
[Comm Cell Meeting] No employee name listed in dropdown for facilitator and minutes taker

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#393]
**Describe the bug**
No employee name listed in dropdown for facilitator and minutes taker
Fiscal year is also not listed

**To Reproduce**
1. Go to Comm Cell Meeting
2. Click on facilitator or minutes taker dropdown
3. No name listed for selection

**Expected behavior**
Names should be listed
Default fiscal year should be selected
3 fiscal years should be listed

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/71701828-f139cd00-2e06-11ea-93a1-97c329750902.png)

**Version (please complete the following information):**
 - Version 3.0

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.1
