### ISSUE TITLE
[Fiscal Year, Month, Year] Set default value for current FY/Month/Year

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#394]
**Describe the bug**
Fix the setting of the default value for either Fiscal Year / Month / Year dropdown on the screens.

1. Resource Planner
2. Sick Leave
3. Vacation Leave
4. Weekly Report
5. Billable Hours
6. Non-Billable Hours
7. KPI Summary
8. Late Tracking
9. Comm Cell Meeting

**To Reproduce**
1. Go to the screens listed. No default value is set for FY, Month, Year as applicable

**Expected behavior**
A default value for FY, Month, or Year should be set on load of the screen.

**Version (please complete the following information):**
 - Version 3.0

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.1
