### ISSUE TITLE
Comcell Clock - Facilitator and Minutes Taker not showing

### ISSUE THREAD

**Issue by jhunellbarcenas** [rsx-labs/aide-frontend#410]
**Describe the bug**
Facilitator and Minutes Taker not showing.

**To Reproduce**
1. Go to Home Screen

**Expected behavior**
Should display the Facilitator and Minutes Taker 

**Screenshots**
![image](https://user-images.githubusercontent.com/39547140/71967545-7c1f2b00-323e-11ea-9ac4-bcbf0a85fabd.png)

**Version (please complete the following information):**
 - Version 3.0.0

**Additional context**

**Comment by GiannCarlo** [comment]
Fixed. Reviewed by Jhunell . Ready for next build

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.1
