### ISSUE TITLE
Assigned Project - Improve naming conventions

### ISSUE THREAD

**Issue by jhunellbarcenas** [rsx-labs/aide-frontend#418]
**Is your feature request related to a problem? Please describe.**
Naming convention used was a bit complicated

**Describe the solution you'd like**
Change the naming convention to much appropriate and easy to recognize.

**Describe alternatives you've considered**

**Additional context**

**Comment by jester0123** [comment]
@charissasylim @jhunellbarcenas 
Changing task description from **Project - Update Functionality** to **Assigned Project - Improve naming conventions** since the update functionality on this module already exists.

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.2.0
