### ISSUE TITLE
Attendance - Incorrect attendance status and no record shown in attendance dashboard

### ISSUE THREAD

**Issue by jhunellbarcenas** [rsx-labs/aide-frontend#420]
**Describe the bug**
Change work location to onsite (WFH, or other besides Eco Tower) will have incorrect attendance status and no record shown in attendance dashboard.

**To Reproduce**
1. Go to Contacts
2. Click on an employee to update
3. Go to Contact Details tab
4. Change Work Location to wfh
5. Click Update button

**Expected behavior**
Attendance record should be shown in attendance dashboard with Onsite status and on resource planner it should be marked as O.

**Screenshots**
-Attendance Dashboard no record display for the employee.
![image](https://user-images.githubusercontent.com/39547140/72309152-2a045c80-36b9-11ea-841a-695b15f14db7.png)

-Resource planner
![image](https://user-images.githubusercontent.com/39547140/72309259-72bc1580-36b9-11ea-8f1a-8ef5ea48773e.png)

**Version (please complete the following information):**
 - Version 3.1.0

**Additional context**
**Please test thoroughly with all possible scenarios with attendance status.**

**Comment by GiannCarlo** [comment]
Fixed. Reviewed by @jhunellbarcenas  .

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.2.0
