### ISSUE TITLE
[Success Register] Unable to add Success Register

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#422]
**Describe the bug**
Unable to add success register due 'Please fill up all required fields!" error message.
All fields are populated already.

**To Reproduce**
1. Go to Success Register
2. Click on the add + button
3. Populate all fields
4. Click create
5. Error message 'Please fill up all required fields!' appears even if all fields are already populated.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/72412196-bd1bc000-37a7-11ea-9a76-82acc8716a28.png)

**Version (please complete the following information):**
 - Version 3.1.0

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.2.0
