### ISSUE TITLE
Task - Unable to update outstanding task

### ISSUE THREAD

**Issue by jsanchez-cwt** [rsx-labs/aide-frontend#424]
**Describe the bug**
Unable to update an outstanding task even it has Project selected already. 

**To Reproduce**
Pre-req: Must have an outstanding task.
1. Go to Task.
2. Click on View My Outstanding Tasks.
3. Select an outstanding task.
4. Click Update button.
5. 'Please select a project' error message will prompt.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/11567332/72482777-d2412f00-3839-11ea-8573-64e44cfa859f.PNG)

**Version (please complete the following information):**
 - Version 3.1.0

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.2.0
