### ISSUE TITLE
[Print] Remove print button/icon on screens

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#428]
**Describe the bug**
Remove print button/icon on screens since this will be replaced by Kool-Aide
1. Contacts List
2. Resource Planner
3. Task Monitoring
4. 3C
5. Action List
6. Lessons Learnt
7. Success Registers
8. Skills Matrix
9. Birthdays (remove Print by dropdown also)

**Version (please complete the following information):**
 - Version 3.1.0

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.2.0
