### ISSUE TITLE
[3C] Update Reference Number formatting to be mm/dd/yyyy

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#432]
**Describe the bug**
Update Reference Number formatting to be mm/dd/yyyy
Ex. existing C27-08/01/2020 should be C27-01/08/2020

--Need to update existing data also

**Version (please complete the following information):**
 - Version 3.1.0

**Comment by jhunellbarcenas** [comment]
@jester0123 please don't forget to do this --Need to update existing data also

**Comment by jester0123** [comment]
@jhunellbarcenas I already manually updated the data before, not sure why it came back to the old format. Anyway this should be added to the build since generated reference format is now in mm/dd/yyyy.

**Comment by jsanchez-cwt** [comment]
Resolved. Tested in version 3.2.0
