### ISSUE TITLE
[Task] Clicking Update shows error 'Please select a project'

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#433]
**Describe the bug**
Clicking Update shows error 'Please select a project'
Project needs to be **re-selected** so that the error does not pop up

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/72781813-2cd4f380-3c5d-11ea-96ac-af948cf7ded7.png)

**Version (please complete the following information):**
 - Version 3.1.0

**Comment by jhunellbarcenas** [comment]
Duplicate issue of #424

**Comment by jhunellbarcenas** [comment]
Issue already fixed by @johnharveysanchez7

**Comment by jhunellbarcenas** [comment]
Closed
