### ISSUE TITLE
[Reports] Use mm/dd/yyyy format for dates instead of dd/mm/yyyy

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#434]
**Is your feature request related to a problem? Please describe.**
Use mm/dd/yyyy format for dates instead of dd/mm/yyyy
Ensure consistency in date format across all reports

**Describe the solution you'd like**
Use mm/dd/yyyy format for dates instead of dd/mm/yyyy

**Comment by trashvin** [comment]
@charissasylim This opened in the kool-aide repo 
https://github.com/rsx-labs/kool-aide/issues/24
for easier tracking and integration to its own release cycle. This aide-frontend issue is now closed.
