### ISSUE TITLE
[Success Register] Double-clicking shows an editable row

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#435]
**Describe the bug**
Double-clicking a success register created by another person displays the row like it is editable.

**To Reproduce**
1. Go to Improvement - Success Register
2. Double click on a row created by another team member
3. See screenshot for how it looks like. One can seem to edit it although it does not save.

**Expected behavior**
Row display should not change to look like it is editable.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/72854901-c13c6600-3cf0-11ea-8eea-fdb1857be585.png)

**Version (please complete the following information):**
 - Version 3.1.0

**Additional context**

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.2.0
