### ISSUE TITLE
Pop Up Messages Consistency

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#436]
**Describe the bug**
Pop up messages are not consistent.
- different messages for the same action
- missing punctuation marks; or excessive punctuation marks (do not used !)

Sample when clicking in closed Action List and 3C -:
In Action List - 'Selected action list has already been closed. Please select open action list.'
In 3C - 'Cannot Edit/Update this Concern. Closed Already'
-- Should probably be phrased as below for both
Selected [Action Item|Concern] is closed. Please select an open [Action Item|Concern].

**Expected behavior**
Pop up messages should be phrased consistently.

**Version (please complete the following information):**
 - Version 3.1.0

**Comment by charissasylim** [comment]
@jhunellbarcenas if you can create a list of all pop up/error messages we use in AIDE that would be helpful so we can finalize. We can move build date if needed just so we can complete this before sending to QA for implementation.

**Comment by jsanchez-cwt** [comment]
Resolved. Tested in version 3.2.0
