### ISSUE TITLE
[Assets] Missing Page Numbering for List of Unapproved Assets module

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#442]
**Describe the bug**
Add page numbering on the List of Unapproved Assets module.

**Version (please complete the following information):**
 - Version 3.1.0

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for next build

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.2.0
