### ISSUE TITLE
Resource Planner - File leave on the same day

### ISSUE THREAD

**Issue by jhunellbarcenas** [rsx-labs/aide-frontend#445]
**Describe the bug**
Allows you to file a leave on a date that is already have a same type of leave.

**To Reproduce**
1. Go to Attendance module
2. Click on add button to file a leave
3. File any kind of leave but not those half-day type of leaves.
4. File again the leave type you filed earlier on the same date.

**Expected behavior**
Sample employee here is Ma'am Karen.
Should not be able to file a leave for that same date with same type of leave.

**Screenshots**
![image](https://user-images.githubusercontent.com/39547140/73055746-6eb5a200-3ec8-11ea-9a45-422f5ae9bad5.png)

![image](https://user-images.githubusercontent.com/39547140/73055918-c227f000-3ec8-11ea-942c-b5339650a344.png)

![image](https://user-images.githubusercontent.com/39547140/73055837-a290c780-3ec8-11ea-8494-747b6cdd731c.png)

**Version (please complete the following information):**
 - Version 3.1.0

**Additional context**
Please also check vacation leave and non-billable hours module. This should also handle the scenario above. Leave credits should not be deducted when doing the scenario above.

**Comment by jsanchez-cwt** [comment]
Resolved. Tested in version 3.2.0
