### ISSUE TITLE
[Resource Planner] Add handling of halfday Onsite work

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#450]
**Describe the bug**
Contacts is sets as Work From Home.
Shift is set as Semi-Flex.
On HSL morning but not yet logged in AIDE.
Once logged in, attendance shows L.
Once HSL is applied, attendance shows HSL/L.

**Expected behavior**
Attendance should be HSL/O.

**Version (please complete the following information):**
 - Version 3.1.0

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.2.0
