### ISSUE TITLE
[Action List] Page numbering goes beyond actual available pages

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#451]
**Describe the bug**
Paging goes Page 4 of 3

**Expected behavior**
Last page should be 'Page 3 of 3'

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/73791574-8d2b6f80-47dd-11ea-93a2-e455d9273469.png)

**Version (please complete the following information):**
 - Version 3.1.o

**Comment by jhunellbarcenas** [comment]
Fixed.

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.2.0
