### ISSUE TITLE
SABAT: Default tab should be "Asset Borrowing"

### ISSUE THREAD

**Issue by beejaguilar** [rsx-labs/aide-frontend#463]
**Describe the bug**
Default tab should be "Asset Borrowing" in SABAT module

**To Reproduce**
1. Click Assets on menu
2. Select Assets Borrowing sub menu

**Expected behavior**
The default tab selected should be Assets Borrowing

**Comment by jsanchez-cwt** [comment]
Resolved. Tested in version 3.2.0
