### ISSUE TITLE
SABAT: Asset borrow confirmation UI display textboxes are editable.

### ISSUE THREAD

**Issue by beejaguilar** [rsx-labs/aide-frontend#464]
**Describe the bug**
SABAT: Asset borrow confirmation UI display textboxes are editable. It can be edited before sending the borrow request

**To Reproduce**
1. Go to Assets menu
2. Select Assets Borrowing submenu
3. On Assets Borrowing tab, click one of the assets listed
5. All the textboxes displayed are editable.

**Expected behavior**
All the textboxes displayed on the confirmation UI must be disabled to avoid error upon sending borrow and return requests.

**Comment by jsanchez-cwt** [comment]
Resolved. Tested in version 3.2.0
