### ISSUE TITLE
SABAT: Asset borrowing request confirmation button must display text Reject instead of Disapprove

### ISSUE THREAD

**Issue by beejaguilar** [rsx-labs/aide-frontend#465]
**Describe the bug**
Asset borrowing request confirmation button must display text Reject instead of Disapprove

**To Reproduce**
1. Go to Assets
2. Select Asset Borrowing submenu
3. Click one of the assets then click "Send Borrow Request"
4. A confirmation UI is displayed with 2 buttons, "Approve" and "Disapprove"

**Expected behavior**
Disapprove button must be changed to Reject.

**Comment by jsanchez-cwt** [comment]
Resolved. Tested in version 3.2.0
