### ISSUE TITLE
[KPI Summary] Adding January 2020 KPI values displays it as January 2019

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#479]
**Describe the bug**
Added January 2020 KPI values but display shows it was added as January 2019.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/74396429-e7b37400-4e4c-11ea-9e7f-951a105f0eac.png)

**Version (please complete the following information):**
 - Version 3.1.0

**Comment by jsanchez-cwt** [comment]
Resolved. Tested in version 3.2.0
