### ISSUE TITLE
Billability - Add Filter View by month and year on weekly report module

### ISSUE THREAD

**Issue by jhunellbarcenas** [rsx-labs/aide-frontend#48]
**Is your feature request related to a problem? Please describe.**
Can't easily keep track of my weekly report

**Describe the solution you'd like**
To have a search button for month and year and also to display only data for the month on datagrid

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jsanchez-cwt** [comment]
Fixed. Ready for Build v2.5
