### ISSUE TITLE
[Non Billable Hours] Dropdown box height too big

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#480]
**Describe the bug**
The height of the dropdown box for month and fiscal year is too big compared with other screens.

**Expected behavior**
Standardized height for textboxes, dropdown box

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/74403350-e50f4980-4e61-11ea-8d70-6f8692866a88.png)

**Version (please complete the following information):**
 - Version 3.1.0

**Comment by jsanchez-cwt** [comment]
Resolved. Tested in version 3.2.0
