### ISSUE TITLE
SABAT: Asset borrowers log must display the logs in descending way

### ISSUE THREAD

**Issue by beejaguilar** [rsx-labs/aide-frontend#483]
**Describe the bug**
Asset borrowers log displays the log in acscending way.

**Expected behavior**
Asset borrowers log must be sorted by log time in descending way o be able to track the asset easier when the logs contains a lot of entries already.

**Comment by beejaguilar** [comment]
Fix was done on the backend branch.

**Comment by jsanchez-cwt** [comment]
Resolved. Tested in version 3.2.0
