### ISSUE TITLE
[Sick Leave] Add remaining Leaves for the employee (like in VL)

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#487]
**Is your feature request related to a problem? Please describe.**
VL screen has Remaining leaves indicated. Add the same for SL.

![image](https://user-images.githubusercontent.com/52391236/74616169-4fc1cd00-5161-11ea-9658-fb2c3207cd9e.png)

![image](https://user-images.githubusercontent.com/52391236/74616189-5bad8f00-5161-11ea-86f4-6b6bc6aaebb1.png)

**Comment by jsanchez-cwt** [comment]
Resolved. Tested in version 3.2.0
