### ISSUE TITLE
Weekly Report - Display task(s) that is not yet completed from previous weekly report

### ISSUE THREAD

**Issue by jhunellbarcenas** [rsx-labs/aide-frontend#49]
**Is your feature request related to a problem? Please describe.**
I always re-add my task that is not yet completed when creating a new weekly report

**Describe the solution you'd like**
Suggesting to automatically include all task(s) that is not yet completed from previous weekly report when creating a new weekly report. 
Note: This includes not only task that is in progress but also those who are **on-hold**, and **not yet started**, **waiting for info** and **return to triage**

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jsanchez-cwt** [comment]
Ready for next build (v2.5)
