### ISSUE TITLE
[Asset Assignment] Other Info does not display value

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#491]
**Describe the bug**
Other info in Asset Assignment does not display any value even if ASSETS.OTHER_INFO column has a value.

Is Other info referring to ASSETS.OTHER_INFO?

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/74708071-7b72af00-5256-11ea-87dc-218d91d873ed.png)

![image](https://user-images.githubusercontent.com/52391236/74708084-86c5da80-5256-11ea-8b92-d05500c44b9a.png)

**Version (please complete the following information):**
 - Version 3.1.0

**Comment by beejaguilar** [comment]
pull request for the fix of this issue is at
AIDE-BACKEND - 491 - [Asset Assignment] Other Info does not display v… #135
https://github.com/rsx-labs/aide-backend/pull/135
