### ISSUE TITLE
[Late Tracking] Move Menu under Attendance instead of Others

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#492]
**Is your feature request related to a problem? Please describe.**
Move the Late Tracking Menu under Attendance instead of Others

Under Attendance you have Resource Planner | Sick Leave | Vacation Leave | Late Tracking
Under Others you have Birthday | Tracker | Comm. Cell Meeting

**Comment by jsanchez-cwt** [comment]
Resolved. Tested in version 3.2.0
