### ISSUE TITLE
Build error on AppVeyor

### ISSUE THREAD

**Issue by trashvin** [rsx-labs/aide-frontend#5]
AppVeyor is reporting a build error

> C:\projects\aide-frontend\AIDEFrontendMaster\GDC.PH.AIDE.CommCellServices\View\MenuPage\Billability\BillabilityVacationLeavePage.xaml(14,14): error MC3074: The tag 'Chart' does not exist in XML namespace 'clr-namespace:System.Windows.Controls.DataVisualization.Charting;assembly=System.Windows.Controls.DataVisualization.Toolkit'. Line 14 Position 14. [C:\projects\aide-frontend\AIDEFrontendMaster\GDC.PH.AIDE.CommCellServices\GDC.PH.AIDE.CommCellServices.vbproj]
> C:\projects\aide-frontend\AIDEFrontendMaster\GDC.PH.AIDE.CommCellServices\View\MenuPage\Billability\BillablesPage.xaml(12,39): error MC3066: The type reference cannot find a public type named 'Chart'. Line 12 Position 39. [C:\projects\aide-frontend\AIDEFrontendMaster\GDC.PH.AIDE.CommCellServices\GDC.PH.AIDE.CommCellServices.vbproj

This is probably an issue on the missing System.Windows.Controls.DataVisualization.Charting. This initially occured too while building it locally, the remediation was to install the package. So this may involve adding the package on the package info.

**Comment by jhunellbarcenas** [comment]
AppVeyor is reporting a build error

> C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Windows.Controls.DataVisualization.Toolkit". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\projects\aide-frontend\AIDEFrontendMaster\GDC.PH.AIDE.CommCellServices\GDC.PH.AIDE.CommCellServices.vbproj]
> C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(2718,5): warning MSB3327: Unable to find code signing certificate in the current user's Windows certificate store. To correct this, either disable signing of the ClickOnce manifest or install the certificate into the certificate store. [C:\projects\aide-frontend\AIDEFrontendMaster\GDC.PH.AIDE.CommCellServices\GDC.PH.AIDE.CommCellServices.vbproj]
> C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(2718,5): error MSB3323: Unable to find manifest signing certificate in the certificate store. [C:\projects\aide-frontend\AIDEFrontendMaster\GDC.PH.AIDE.CommCellServices\GDC.PH.AIDE.CommCellServices.vbproj]

We've uploaded the package folder to fix last issue. 
I think this issue is because of the clickonce i tried using on my solution

**Comment by trashvin** [comment]
Im closing this issue, it will be revisited once Ive migrated CI on Azure Devops.
