### ISSUE TITLE
[Team Attendance Legend] Holiday has no color

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#500]
**Describe the bug**
Holiday does not show any color.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/75124918-4d291f80-56ed-11ea-87e5-8f231f5fdeb1.png)

**Version (please complete the following information):**
 - Version 3.2.0

**Comment by jhunellbarcenas** [comment]
Fixed. Tested in version 3.2.1
