### ISSUE TITLE
[Create Project] Displays an extra page with empty list

### ISSUE THREAD

**Issue by trashvin** [rsx-labs/aide-frontend#562]
**Describe the bug**
The screen displays 1 extra page with empty list

**To Reproduce**
1. Go to Create Project
2. Navigate the list of projects

**Expected behavior**
After displaying the last batch of projects, the page should end there. 

**Screenshots**

**Version (please complete the following information):**
 - Version [e.g. 3.3.1]

**Additional context**

**Comment by trashvin** [comment]
@charissasylim , can we close this? no longer reproducible in the latest build
![image](https://user-images.githubusercontent.com/6635163/82877018-4029ff80-9f6c-11ea-9d3f-dd2c5d18fe97.png)

**Comment by charissasylim** [comment]
Ok

**Comment by charissasylim** [comment]
working in  3.3.4
