### ISSUE TITLE
[KPI Summary] Adding KPI Summary for April 2020 adds Overall to January 2020

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#565]
**Describe the bug**
Adding KPI Summary for April 2020 adds Overall to January 2020
Chart also shows entries under January 2020
KPI 3 Legend Text Not Showing

**Expected behavior**
Overall should also be in April 2020

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/81546080-6cf6e800-93ac-11ea-9ed4-6dabc52fd693.png)

**Version (please complete the following information):**
 - Version 3.3.2

**Comment by chriscg** [comment]
Note: When adding KPI Summary, please add kpi entry even if kpi target and kpi actual is zero. Limitation of display of chart and table. Overall value computation will still be correct as fixed.
