### ISSUE TITLE
[Workplace Audit Schedule] Arrange auditor list of names alphabetically

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#569]
**Describe the bug**
Arrange auditor list of names alphabetically by the value being displayed for easier searching of name. 

**Version (please complete the following information):**
 - Version 3.3.2

**Comment by charissasylim** [comment]
Changes made on sp_GetAuditSched in AIDE .100 DB

**Comment by charissasylim** [comment]
Since [sp_GetNicknameByDeptID] is ordered by Last Name, please display names in dropdown as LastName, FirstName instead of Nickname just like in all other screens.

**Comment by trashvin** [comment]
@charissasylim , may sp changes ka na kailanan icheckin? i have the code chages sa aide

**Comment by charissasylim** [comment]
For this one need ata change sa UI to pass correct display type.
