### ISSUE TITLE
[Workplace Audit Schedule] Missing FY_Week #1 for FY2020

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#570]
**Describe the bug**
Dropdown for week selection in April starts April 6th. Missing April 1.
Is this OK?

**Version (please complete the following information):**
 - Version 3.3.3

**Comment by chriscg** [comment]
Because there was no record for that week.

**Comment by trashvin** [comment]
Is it because April 1 to 3 is part of a week range that includes date from the previous FY?

**Comment by trashvin** [comment]
@charissasylim , @chriscg  can we close this issue?

**Comment by charissasylim** [comment]
Ok

**Comment by trashvin** [comment]
Working as expected
