### ISSUE TITLE
[Quarterly Workplace Audit] No data being displayed even if DB contains the data needed

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#575]
**Describe the bug**
No date being displayed even if DB contains the data needed

**Version (please complete the following information):**
 - Version 3.3.3

**Comment by charissasylim** [comment]
Made changes on sp_getQuarterlyAuditor in AIDE .100 DB
Data is now getting displayed.
@GiannCarlo can you review the changes on the SP please. Changes done below on SP.
- DateValue is changed to +1 if COUNT is 1,2,3. I am assuming this is Jan-Mar of next FY.
- Remove -1 for the DateValue in the else condition of COUNT
- Commented out the where condition in the last SELECT * FROM #SummaryQUARTERLYAuditor w

**Comment by charissasylim** [comment]
@GiannCarlo @marvin On QA view, quarterly audit records are still not displaying in 3.3.4. You can try running aide from .100 to test.

**Comment by GiannCarlo** [comment]
@charissasylim , pushed new changes in displaying Workpalce Audit Quarterly on QA view. 
associated with **https://github.com/rsx-labs/aide-backend/commit/7b11e0733286d3fa9672a4cfa371e2ba6739adb5**

**Comment by charissasylim** [comment]
working in 3.3.5
