### ISSUE TITLE
[Attendance] If employee is late, attendance is set to present even if employee is wfh

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#577]
**Describe the bug**
If employee is late, attendance is set to present even if employee is wfh in contacts location

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/82539976-eb0f7780-9b80-11ea-9911-84725b36b70b.png)

**Version (please complete the following information):**
 - Version 3.3.3

**Comment by chriscg** [comment]
The way it was implemented is not good, it will have a big impact on changing stored procedure, codes and even reports. So I'm not sure, if we really have to fix or redo this? I guess, we should not consider late as a status code. We only have legends present, VL, SL, On-site, etc and each represented by a status code. If an employee is late then it is automatically assumed as present without even checking if he/she is really present or on-site.

**Comment by charissasylim** [comment]
Let’s lower the priority on this.

**Comment by trashvin** [comment]
Assigning this to me,  i have the working fix. no reports will be affected and the status '11' will still be used on the attendance table.
