### ISSUE TITLE
[Lessons Learnt] Unable to add Lessons Learnt

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#587]
**Describe the bug**
Unable to add Lessons Learnt even if message said that lesson has already been added.

**To Reproduce**
1. Add a lesson learnt

**Version (please complete the following information):**
 - Version 3.3.3

**Comment by chriscg** [comment]
Cause by a trigger [tr_parseLessonToSummary] which is not supposed to be for AIDE. Already deleted the trigger.

**Comment by charissasylim** [comment]
@trashvin @chriscg Tested by @GiannCarlo in 3.3.4 and still not working.

**Comment by charissasylim** [comment]
@trashvin @chriscg working now in 3.3.4 after chris removed trigger from DB
