### ISSUE TITLE
Daily workplace audit screen does not default to the current week

### ISSUE THREAD

**Issue by trashvin** [rsx-labs/aide-frontend#595]
**Describe the bug**
Daily workplace audit screen does not default to the current week. It my test, it defaults to the previous week.

**To Reproduce**
1. Go to Workplace Audit->Daily WA
2. Check the week display

**Expected behavior**
Week display shows the previous week and not current week. The Auditor list also displays the previous week value.

**Screenshots**
![image](https://user-images.githubusercontent.com/6635163/83213525-e8baa800-a194-11ea-9a7f-fd432341ebf4.png)

**Version (please complete the following information):**
 - Version 3.3.4

**Comment by charissasylim** [comment]
Fixed 3.3.6
