### ISSUE TITLE
Workplace audit icons are not consistent with other icons

### ISSUE THREAD

**Issue by trashvin** [rsx-labs/aide-frontend#597]
**Describe the bug**
Workplace audit icons are not consistent with other icons. Other icons have clear white fills, the workplace icons have other colors. 

**To Reproduce**
1. Go to Workplace Audit
2. Look at the main Workplace Audit and sub button menu icons

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6635163/83213957-0a685f00-a196-11ea-8408-bbed4d968d71.png)

**Version (please complete the following information):**
 - Version [e.g. 3.3.4]

**Comment by charissasylim** [comment]
fixed in 3.3.5
