### ISSUE TITLE
[Problem Solving] Double-check if scrollbar appears if there are many PS items

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#598]
**Describe the bug**
Double check if a scrollbar appears if there are more than 4 or 5 PS items in the Problem table.

**To Reproduce**
1. Create more than 4 or 5 Problem
2. Check if scrollbar or page numbering appears

**Expected behavior**
Should be able to see all Problems via scrollbar or page numbering

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/83214136-6b903280-a196-11ea-948d-990d789bcce0.png)

**Version (please complete the following information):**
 - Version 3.3.4

**Comment by chriscg** [comment]
Verified with auto-scroll:
![image](https://user-images.githubusercontent.com/13752070/83379232-9df79500-a40d-11ea-9fd0-1ac8e57c22e7.png)
