### ISSUE TITLE
[Weekly Workplace Audit] Giann was still unable to save data for this module

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#599]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**

**Additional context**

**Comment by GiannCarlo** [comment]
Hi Ms @charissasylim , this was handled by  #599_-_Workplace_Audit_-_able_to_save_/select_schedule_if_you_were_the_assigned_employee

PR contains 
 Workplace Audit -
  - Able to select schedule if you were the assigned employee,
  - Fixed bug when pressing others schedule and selecting different day/month/week/ will display blank schedule. 
 - Fixed remarks & Status when saving workplace audit.

I haven't merged it yet. I requested sir @chriscg  in the PR for review. :) hehe
