### ISSUE TITLE
AIDE should be able to handle locally set date time format

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#613]
**Describe the bug**
AIDE should be able to adapt to local date and time setting on the machine where it is running.

For now, AIDE is only able to handle mm/dd/yyyy format

**Version (please complete the following information):**
 - Version 3.3.5

**Comment by charissasylim** [comment]
@chriscg Issue seen specifically in the following screens/scenario by QA.
1. Click Assets tab - Asset Assignment tab - Double click Asset ID nnn - App error occurs
2. Click Attendance - App error occurs
3. Click Resource Planner - No data gets displayed
4. Add 3C - Data not saved due to date issue
5. Add Action List - Unable to input future dated due date

Focus on fixing the date issue. Not recommending changing the date format in display to avoid regression testing.

**Comment by chriscg** [comment]
Cannot recreate issue for Assets

**Comment by charissasylim** [comment]
Reopen if issue occurs
