### ISSUE TITLE
[Workplace Audit] Date Checked is saved incorrectly in DB

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#614]
**Describe the bug**
Date checked is saved incorrectly in DB.
Date checked June 3, 2020 is saved as 2020-03-06 thus displayed as March 6 , 2020

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/83579426-d44b2680-a56b-11ea-899a-0281630c6157.png)

**Version (please complete the following information):**
 - Version 3.3.5

**Comment by chriscg** [comment]
![image](https://user-images.githubusercontent.com/13752070/84097157-458c4d00-aa36-11ea-823c-1a694dd5ce14.png)

**Comment by chriscg** [comment]
Please try again on next build.

**Comment by charissasylim** [comment]
fixed 3.3.6
