### ISSUE TITLE
[Workplace Audit] Takes a while for screen to display when selecting a Month

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#615]
**Describe the bug**
It takes a while for the screen to be displayed when selecting a month from the dropdown.
Double check if there is need for optimization.

**Screenshots**
Remains in this screen a while.
![image](https://user-images.githubusercontent.com/52391236/83579577-373cbd80-a56c-11ea-80d0-f35da0010633.png)

**Version (please complete the following information):**
 - Version 3.3.5

**Comment by chriscg** [comment]
This has been fixed by this commit: https://github.com/rsx-labs/aide-frontend/commit/d87de51c84b494460df85b15f547884b8abd88a9

**Comment by charissasylim** [comment]
Fixed 3.3.8
