### ISSUE TITLE
[Login] Check Process for OTP sending

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#617]
**Describe the bug**
If outlook email is not accessiblel, AIDE will automatically send AIDE the username. AIDE will query the db for that username and send OTP to Fujitsu Email where user can use OWA instead.

Note: AIDE is unable to send email to external email address

**Version (please complete the following information):**
 - Version 3.3.5

**Comment by trashvin** [comment]
@charissasylim  lets change the proposed design,  that would entail more work. 

New proposal : If outlook is not working, we'll just ask them their office email then send the otp in the office mail. Assumption is that the user must have to access their office email to be able to use AIDE.

**Comment by charissasylim** [comment]
fixed 3.3.6
