### ISSUE TITLE
Unable to add a new annoucement

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#62]
**Describe the bug**
Clicking Add Announcement Create button after inputting the Title and message shows an error message 'Please Fill Up All Fields!'

**To Reproduce**
1. Go to Dashboard
2. Click the Announcements + button
3. Input Title and Message and click the Create button
4. See error 'Please Fill Up All Fields!'

**Expected behavior**
Add should be successful

**Screenshots**
![Annoucement Error](https://user-images.githubusercontent.com/52391236/60489403-dc08a800-9cd6-11e9-9cb6-dc834ca96f3d.PNG)

**Version (please complete the following information):**
 - Version 2.4

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.5
