### ISSUE TITLE
UI Tab has inconsistencies

### ISSUE THREAD

**Issue by trashvin** [rsx-labs/aide-frontend#620]
**Describe the bug**
UI Tabs in some places are not UI acceptable. Some have tab header misaligned especially if the screen ratio is different from normal screens

**To Reproduce**
1. example 1 Go to 'Asset' -> "Asset Assignment" -> "My Assets"
2. example 2 Go to 'Asset' -> "Asset Borrowing"

**Expected behavior**
Tab header alignment should be consistent regardless of screen ratio.  Follow the "Contact List" design to Tabs

**Screenshots**
![image](https://user-images.githubusercontent.com/6635163/83933229-62781480-a7d9-11ea-8a12-7db0cb6a59e6.png)

![image](https://user-images.githubusercontent.com/6635163/83933256-92bfb300-a7d9-11ea-9922-00416866dc28.png)

**Version (please complete the following information):**
 - Version3.3.5

**Comment by charissasylim** [comment]
Fixed 3.3.6
