### ISSUE TITLE
[Skills Matrix] Not all skills data are getting displayed

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#634]
**Describe the bug**
Not all skills data are getting displayed. Found in QA.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/85001630-7aab4480-b186-11ea-8ecc-ef9f64d39ed3.png)

**Version (please complete the following information):**
 - Version  3.3.6

**Additional context**

**Comment by trashvin** [comment]
@charissasylim @chriscg   cant find any commit that resolves this issue.
![image](https://user-images.githubusercontent.com/6635163/85044358-14dbae80-b1c0-11ea-8972-be938a585742.png)

**Comment by charissasylim** [comment]
Fixed 3.3.7
