### ISSUE TITLE
[Main screen] Facilitator and minute taker for commcell is not displayed if its a Friday

### ISSUE THREAD

**Issue by trashvin** [rsx-labs/aide-frontend#639]
**Describe the bug**
The Facilitator and minute taker for commcell is not displayed if its a Friday

**To Reproduce**
1. Open AIDE on a Friday
2. Observe the facilitator and minute taker display of the commcell clock

**Version (please complete the following information):**
 - Version 3.3.7

**Comment by charissasylim** [comment]
Fixed 3.3.8
