### ISSUE TITLE
[Team Status Weekly Report] Marvin Total Hours shows 14 hours but Weekly Status Hours shows 40 hours.

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#641]
**Describe the bug**
Marvin Total Hours in Team Status Weekly Report view shows 14 hours but Weekly Status Hours in Marvin's Weekly Report shows 40 hours.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/85242586-06b4b900-b472-11ea-8a87-7d468ec16ba0.png)

![image](https://user-images.githubusercontent.com/52391236/85242668-44194680-b472-11ea-914f-16b5c1af952b.png)

![image](https://user-images.githubusercontent.com/52391236/85242660-3cf23880-b472-11ea-9ec6-bb4c561649b5.png)

*Version (please complete the following information):**
 - Version 3.3.7

**Comment by trashvin** [comment]
Date error / missing entry.  Data fixed.
