### ISSUE TITLE
[Create Project] UI shows a large gap if the user is not a manager

### ISSUE THREAD

**Issue by trashvin** [rsx-labs/aide-frontend#642]
**Describe the bug**
UI shows a large gap if the user is not a manager. The space is supposedly occupied by the additional UI elements for managers.

**To Reproduce**
1. Login as regular employee
2. Go to 'Projects'

Note check the "Assign project screen too"

**Expected behavior**
The container for the manager only UI elements should be collapsible so that the spaces will be occupied by the elements below it.

**Screenshots**
![image](https://user-images.githubusercontent.com/6635163/85275970-af373d00-b4b3-11ea-9646-62be307922e9.png)

**Version (please complete the following information):**
 - Version 3.3.7

**Comment by charissasylim** [comment]
fixed 3.3.9
