### ISSUE TITLE
[Workplace Audit] The icon in the workplace audit screen is missing

### ISSUE THREAD

**Issue by trashvin** [rsx-labs/aide-frontend#643]
**Describe the bug**
The icon in the workplace audit screen is missing. For consistency , an icon should be added.

**To Reproduce**
1. Go to Workplace Edit

**Expected behavior**
For consistency , an icon should be added.

**Screenshots**
![image](https://user-images.githubusercontent.com/6635163/85276453-69c73f80-b4b4-11ea-94c3-e676410a594f.png)

**Version (please complete the following information):**
 - Version 3.3.7
**Additional context**

**Comment by charissasylim** [comment]
fixed 3.3.8
