### ISSUE TITLE
[Contact List] Unable to edit the work shift for some employees

### ISSUE THREAD

**Issue by trashvin** [rsx-labs/aide-frontend#646]
**Describe the bug**
Description from helpdesk : Work shift cannot be updated for Grace Singian

**To Reproduce**
In Contact List, edit Grace Singian and update shift to Flexi. 
Click Update and a pop up message "Contacts have been updated". 
click OK. 
When viewed again, the shift is still Semi-flex

**Expected behavior**
It should update the workshift schedule

**Version (please complete the following information):**
 - Version 3.3.7

**Additional context**
This can be reproduced in the dev env

**Comment by charissasylim** [comment]
Fixed 3.3.8

**Comment by charissasylim** [comment]
Reopened since issue still exists in 3.3.8

**Comment by charissasylim** [comment]
confirmed fixed by jiji 3.3.9
