### ISSUE TITLE
[Email Notif] Resource Planner Email Notification sends twice in 1 day

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#649]
**Describe the bug**
 Resource Planner Email Notification received twice in 1 day but content of both emails shows 10AM.
1. 10AM
2. 11-ish AM

Is this WAD? Members missing entry for the day already updated logged in to AIDE after 10AM email (before 11-ishAM email).

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/85830559-63400d00-b7bf-11ea-82ea-650f6eb7a433.png)

![image](https://user-images.githubusercontent.com/52391236/85830749-af8b4d00-b7bf-11ea-8b28-c6076f998aa4.png)

**Version (please complete the following information):**
 - Version 3.3.7

**Comment by charissasylim** [comment]
Daily Workplace audit reminder sent twice
![image](https://user-images.githubusercontent.com/52391236/85963646-42f39680-b9e9-11ea-86eb-30668847ed3c.png)

**Comment by chriscg** [comment]
I checked the code, no duplicate sending of email for each module. It could be a network issue or common outlook issue. See https://www.nucleustechnologies.com/blog/reasons-for-duplicate-emails-in-outlook/#:~:text=MS%20Outlook%20generates%20duplicates%20for,all%20the%20MS%20Outlook%20versions.'

**Comment by charissasylim** [comment]
June 30 didnt send duplicate email for resource planner.
