### ISSUE TITLE
[Comm Cell] Incorrect Facilitator and Minutes Taker for the week is displayed

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#666]
**Describe the bug**
Incorrect facilitator and MT for the week is being displayed.
Previous week's facilitator and MT are being displayed.

**Version (please complete the following information):**
 - Version 3.3.7

**Comment by trashvin** [comment]
@charissasylim  is this not correct ?
![image](https://user-images.githubusercontent.com/6635163/86678242-f3d3e400-c02e-11ea-890b-fe4bf7bb8f9b.png)

**Comment by charissasylim** [comment]
Week range is defined as saturday to friday.
Adjusted QA data to fit into defined week range.
