### ISSUE TITLE
[Week Range] Current week range is set as Saturday to Friday

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#669]
**Describe the bug**
Current week range is set as Saturday to Friday which was based on OTL. 
Check if we can change this more appropriately to be Sunday to Saturday.

As confirmed with Harvey, this will have an impact on Weekly Report module.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Version 3.3.8

**Additional context**

**Comment by charissasylim** [comment]
SAP  is also on Saturday to Friday week. So do we still need to change this?

**Comment by trashvin** [comment]
Lets make this a low priority and not include this on the next build. Eventually, we'll have to make this configurable by department so they can control their reports etc..

**Comment by charissasylim** [comment]
Since AIDE will no longer be implemented in GDC, keep as is.
