### ISSUE TITLE
3C Seems to Get CLOSED Automatically

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#68]
**Describe the bug**
3C items got closed at end of the day.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/61116580-4be11480-a4c7-11e9-9d67-ce38dc1916b3.png)

**Version (please complete the following information):**

**Additional context**

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.5
