### ISSUE TITLE
[Attendance] No color for 'Other Leave'

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#695]
**Describe the bug**
No color for 'Other Leave'
Double check if all leaves have color assigned

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Version 3.3.9

**Additional context**

**Comment by trashvin** [comment]
Fix will use the same indicator as the "On Vacation"

**Comment by charissasylim** [comment]
Fixed 3.4.0.1
