### ISSUE TITLE
Assign Project

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#81]
Instead of First Month/Second Month/Third Month, this should either be on a monthly basis or weekly basis or start and end dates... need to brainstorm on this functionality..

**Comment by jhunellbarcenas** [comment]
As discussed this table should only contains Name column and Project column

**Comment by chriscg** [comment]
Fixed

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
Confirmed Fixed on v2.8.0
