### ISSUE TITLE
Consistency in Labels

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#83]
Minor corrections below.
Contacts
1.	‘Select job position’ -> ‘Select role’
2.	‘Select Marital Status’ -> ‘Select marital status’
3.	‘Select Work Shift’ -> ‘Select work shift’
4.	‘Nick Name’ -> ‘Nickname’

Weekly Report
1.	Missing Reports message -> ‘ALL REPORTS HAVE BEEN SUBMITTED’

----Check other screens for consistency

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.6
