### ISSUE TITLE
Unable to update Project Billability from UI

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#85]
FAI-Admin Project should be External Billability

**Comment by charissasylim** [comment]
Unable to update Project Billability from UI
FAI Admin displaying as Internal Billability and counted as non billable in Billable hours but database should billability value = 1 already.

**Comment by jhunellbarcenas** [comment]
Issue is on datagrid not updating after reload when update is done.

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.6
