### ISSUE TITLE
Deduction of leaves if employees come in for work instead of taking filed VL

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#86]
An employee files for VL
The employee went to work instead of using the VL
When employee logs in to AIDE, the attendance will show as Present but the VL does not get deducted.

Expected behaviour
VL should be deducted

**Comment by jhunellbarcenas** [comment]
For next build (2.7) @jester0123 please create a UI for this. As discussed, 2 tabs will be created on resource planner pop-up window. A tab to cancel any planned leaves and the other one is for managers only a list of unapproved leaves.

**Comment by charissasylim** [comment]
@jester0123 hi jester, have you started to work on this? if not, will you be able to insert this into your current workload?

**Comment by jhunellbarcenas** [comment]
@johnharveysanchez7 Please work as discussed on my email

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.1
