### ISSUE TITLE
Update in Commcell Meeting showns different naming format

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#89]
**Describe the bug**
Updated facilitator and minutes taker names are displayed in full name uppercase.
Old data displayed as firstname camel case.

**To Reproduce**
Update facilitator and minutes taker.

**Expected behavior**
Names should be displayed in the same format for all months.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/61690531-1efcef00-ad5c-11e9-9940-1e5ab917a1e1.png)

**Version (please complete the following information):**
 - Version 2.5

**Comment by jhunellbarcenas** [comment]
Camel case format for first name is due to manual insertion of data before. Expected Value should be in ALL CAPS Format for first name. We can update this on AIDE to have it in ALL CAPS format

**Comment by jhunellbarcenas** [comment]
Camel case format for first name is due to manual insertion of data before. Expected Value should be in ALL CAPS Format for first name. We can update this on AIDE to have it in ALL CAPS format.
@charissasylim

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.6
