### ISSUE TITLE
Different tables should not be saving the employee name but instead the employee ID if needed

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#90]
The following tables should be saving employee ID instead of name.
1. ACTIONLIST - What is the purpose of the NICK_NAME? Should this be OWNER instead? Assuming EMP_ID is the employee who inputted the action?

2. COMCELL_MEETING - FACILITATOR and MINUTES_TAKER should contain the employee ID instead of name.

2. RESOURCE_PLANNER - Why do we need to have EMPLOYEE_NAME in the table?

**Comment by jhunellbarcenas** [comment]
For QA Testing v2.7 build

**Comment by charissasylim** [comment]
@chriscg Has change been applied to ACTIONLIST too? Table still contains NICK_NAME column.

**Comment by charissasylim** [comment]
COMCELL_MEETING  and RESOURCE_PLANNER already confirmed fixed in v2.8.0

**Comment by chriscg** [comment]
> @chriscg Has change been applied to ACTIONLIST too? Table still contains NICK_NAME column.

ACTIONLIST cannot be modified at this time, needs enhancement. Will open a separate issue instead.
