### ISSUE TITLE
Mandatory Fields should have * indicated

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#93]
**Describe the bug**
ALL mandatory fields should consistently have the * to indicate that the field is mandatory.
This should apply to all screens.

**To Reproduce**
Example in inputting contact details, no * is shown and when i clicked submit, it told me to input all mandatory fields but i was not sure which one was mandatory.

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.6
