### ISSUE TITLE
Skills - Displays a list project data after a new install.

### ISSUE THREAD

**Issue by bwtlim** [rsx-labs/aide-frontend#94]
Description: 
Displays a list of project data after a new install.

Steps:
1. Install the AIDE app
2. Launch the AIDE app and log-in
3. Click Skills button

Actual Result:
![Skills](https://user-images.githubusercontent.com/53248759/61767309-7790c280-ae16-11e9-913c-cbf71ae24d0f.JPG)

Skills Matrix table should not display the list of projects after a new install. Table should be empty.
Please see attached screenshot.

 - Version 2.5

**Comment by jhunellbarcenas** [comment]
Fixed. Skills of dev team are now not visible to other divisions.
Additional notes:
- Since AIDE does not have yet a data maintenance. Insertion of QA/Other department's skills are done through back-end (SQL Script). Will close this now. Thank you
@bwtlim
