### ISSUE TITLE
Contact List - No roles for QA.

### ISSUE THREAD

**Issue by bwtlim** [rsx-labs/aide-frontend#96]
**Description:**
Contact List - No roles for QA.

**Steps:**
1. Click Contacts List
2. Click the '+' button
3. Click the 'Select Role' dropdown

**Actual behavior**
Junior, Mid, and Senior roles available are for developers only.

**Expected behavior**
Add Junior, Mid, and Senior roles for QA.

**Screenshots**
![Roles](https://user-images.githubusercontent.com/53248759/61769302-62b72d80-ae1c-11e9-9d5c-46c386f94415.jpg)

**Version (please complete the following information):**
 - Version 2.5

**Comment by jester0123** [comment]
@bwtlim 
This will be resolve in next build. We already changed the job title to "Manager,Senior,Mid,Junior,Trainee" instead. Thank you.

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.6
