### ISSUE TITLE
Comcell Time - Unable to input correct minutes if it is ':00'.

### ISSUE THREAD

**Issue by bwtlim** [rsx-labs/aide-frontend#97]
**Describe the bug**
Comcell Time - Unable to input correct minutes if it is ':00'.

**To Reproduce**
1. In the Home screen, click the '+' button of Comm. Cell Time
2. Select Day - Wednesday
3. Enter Hours - 10
4. Enter Minutes - 00
5. Click Update

**Actual behavior**
Displays error message, "Please fill up all fields!"

**Expected behavior**
Should allow entering of ':00' minutes.

**Screenshots**
![CommCellTime](https://user-images.githubusercontent.com/53248759/61769555-3ea81c00-ae1d-11e9-956e-e13f41d45528.JPG)

**Version (please complete the following information):**
 - Version 2.5

**Comment by jester0123** [comment]
@bwtlim 
This is working on previous builds. There's just an error in merging the latest source that overwrite the working file with the nonworking file. This will be resolve in next build. Thank you.

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2,6
