### ISSUE TITLE
Contact Lists - New contact not added if contact info includes a mobile number.

### ISSUE THREAD

**Issue by bwtlim** [rsx-labs/aide-frontend#98]
**Describe the bug**
Contact Lists - New contact not added if contact info includes a mobile number.

**To Reproduce**
1. Click Contacts List
2. Click '+' button
3. Enter employee information. (Do not forget to enter the mobile number.)
4. Click Create

**Actual behavior**
New contact is not added.
We tried to add another contact. This time he/she does not have a mobile number. After clicking the Create button, contact is added to the Contacts List table.

**Expected behavior**
Should be able to add a new contact with or without the mobile number.

**Version (please complete the following information):**
 - Version 2.5

**Comment by jester0123** [comment]
@bwtlim 
Currently, System will only process mobile number with 10 digits. The only problem here is that we didn't set the max length of mobile entry to 10 but if entry goes with 10 digit, the system will process the insertion of new employee. On the next build we are going to set it to 11 digit. For the mean time lets input 10-digit mobile number. (ex. 9160092356). Thank you.

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.6
