### ISSUE TITLE
Contact List - New Contact not added if Birth date has value

### ISSUE THREAD

**Issue by chloecastillo** [rsx-labs/aide-frontend#99]
Steps to Replicate:

1. Add new Contact
2. Enter all information available in the window. (Ensure that Birth date has value)
3. Click Create button

Expected: Contact is saved and visible in the List.
Actual: Contact is not saved.

Note: The issue above was discovered after inputting a Contact details without a birth date.

**Comment by jhunellbarcenas** [comment]
Fixed. Ready for v2.6
